### ISSUE TITLE
Configure New Website

### ISSUE THREAD

**Issue by dlebauer** [az-digitalag/organization#1]
The website is datascience.cals.arizona.edu. Everyone has administrative access and is encouraged to poke around; you can log in here: https://datascience.cals.arizona.edu/user and make sure to use webauth

![image](https://user-images.githubusercontent.com/464871/54319410-b67c5500-45a6-11e9-902b-1ed39877226d.png)

We should have the following tabs at the top:

* Home
* Projects
   * Publications
   * Funding
   * Software
   * Data
* Contact
* People
* News (publications? updates? blog?)

Top right: links to OSF and GitHub pages?

**Comment by julianpistorius** [comment]
@dlebauer Done?

**Comment by dlebauer** [comment]
done! now moving on to the hugo version!
