### ISSUE TITLE
Architecture diagram for UA Pipeline

### ISSUE THREAD

**Issue by julianpistorius** [az-digitalag/organization#103]
Particularly with how it integrates with CyVerse

Make slides or google drawing or lucidchart

**Comment by Chris-Schnaufer** [comment]
@julianpistorius Please put an estimate on this ticket

**Comment by julianpistorius** [comment]
@Chris-Schnaufer Done. Thanks for catching that.

**Comment by Chris-Schnaufer** [comment]
Sprint 20 had draft developed

**Comment by julianpistorius** [comment]
Ask Sateesh to use the existing diagrams from Max's TERRA REF slides. 'Business/Science logic' should not be fundamentally different.

**Comment by dlebauer** [comment]
what is required to wrap this up?

**Comment by julianpistorius** [comment]
Sorry @dlebauer, just saw this notification. Is this still relevant?
