### ISSUE TITLE
Separate tickets, OKRs, and Scrum from Project Management wiki

### ISSUE THREAD

**Issue by dlebauer** [az-digitalag/organization#111]
This page should be split up https://osf.io/tzmhp/wiki/Project%20Management/

**Comment by dlebauer** [comment]
this has been completed

![image.png](https://images.zenhubusercontent.com/583f321cb9dc3c622022c169/a6ddd3d7-ba5f-4630-8fbc-be39fd9ff9e7)

**Comment by Chris-Schnaufer** [comment]
Moving to Done since David indicates this has been done
