### ISSUE TITLE
Current state of cache server 'low-water mark'

### ISSUE THREAD

**Issue by julianpistorius** [az-digitalag/organization#116]
What’s the state of the gantry cache server 60% 'low-water mark' issue? 

Via https://hackmd.io/E4mtCmlETR2akIQWNS8KEg

**Comment by dlebauer** [comment]
bring up in convo w/ sean, I think he has a file containing all of the result of a du or dh thing

**Comment by julianpistorius** [comment]
I couldn't get it done this sprint. I still don't have SSH access to the gantry cache server. UITS never got back to me with an IP subnet range. 

Now seriously considering asking for a bastion host in NCSA.

**Comment by dlebauer** [comment]
@julianpistorius NCSA does not want to / is not funded manage the server any longer. If UITS hasn't gotten back best to follow up to get the permission you need (ask Blake or Matt?).

**Comment by julianpistorius** [comment]
OK. I'll do that. Please push this to next sprint @Chris-Schnaufer

**Comment by julianpistorius** [comment]
Update: Have SSH access to the gantry cache server now, and have reached out to Sean to find out more.

**Comment by Chris-Schnaufer** [comment]
Waiting on Sean's response

**Comment by julianpistorius** [comment]
I think this might be close to being solved thanks to the `ncdu` database highlighting where the space was used.
