### ISSUE TITLE
Create OSF page to document hiring process

### ISSUE THREAD

**Issue by KristinaRiemer** [az-digitalag/organization#117]
Include application and interview rubrics, and email templates. This is to reduce the amount of work done later while hiring that has already been worked out.

**Comment by KristinaRiemer** [comment]
The initial version of the general hiring process details, including form emails, are on [the new OSF hiring page](https://osf.io/tzmhp/wiki/Hiring/). @julianpistorius would you be able to review this for missing or incorrect content?

**Comment by julianpistorius** [comment]
Sure can @KristinaRiemer.

**Comment by julianpistorius** [comment]
@Chris-Schnaufer - Could you please double-check, especially the email text?

**Comment by julianpistorius** [comment]
@KristinaRiemer Looks good to me! Thanks very much for doing that. I'm glad you've captured all our hard work in something reproducible, and which will save us time in the future.

**Comment by KristinaRiemer** [comment]
Closing this issue, review still needs to be finished, see [this followup issue](https://github.com/az-digitalag/organization/issues/124).
