### ISSUE TITLE
Enable projects menu

### ISSUE THREAD

**Issue by dlebauer** [az-digitalag/organization#119]
1. Need to move content from individual project pages to the main project page. 
2. Under projects, there should be a section called 'software' with this list and content from individual software pages
    * _TERRA REF_ An open access data and computing platform to support high throughput penotyping [web](https://terraref.github.io/) [github](https://github.com/terraref/)
    * _PEcAn_ (Predictive Ecosystem Analyzer), a model-data synthesis framework: [code](https://github.com/PecanProject/pecan); [project website](https://pecanproject.org); [web interface](https://pecan.ncsa.illinois.edu/pecan)
    * _BETYdb_, A database of plant traits, crop yields, and computational provenance [code](https://github.com/PecanProject/bety); [web interface](https://betydb.org)
    * _BioCro_: crop productivity and ecosystem services simulator: [code](https://github.com/ebimodeling/BioCro)
    * Ecosystem Climate Regulation Services Calculator: [code](https://github.com/ebimodeling/ghgvc); [demo](http://www.ecosystemservicescalc.org)

**Comment by julianpistorius** [comment]
@dlebauer it looks like you started this already, but things are not linked up properly. Not sure what the status of this is. 

Let me know what you want to do. I can just publish what you made.

**Comment by dlebauer** [comment]
@julianpistorius I updated the description above ... but I can take this on.

**Comment by Chris-Schnaufer** [comment]
Removing Julian - so David's the only one on this ticket now

**Comment by dlebauer** [comment]
https://datascience.cals.arizona.edu/

not sure why but it works when I am signed in:

![image.png](https://images.zenhubusercontent.com/583f321cb9dc3c622022c169/f6deda7b-81a1-47a0-8f03-16a08f7759bf)

But not in a new private browser (despite clearing cache)

![image.png](https://images.zenhubusercontent.com/583f321cb9dc3c622022c169/71d94f26-037c-4850-b1ed-5debe6284212)

**Comment by Sithyphus** [comment]
When I tried accessing this link I received a page not found.

**Comment by dlebauer** [comment]
@Sithyphus the link is https://datascience.cals.arizona.edu/projects-overview ... I'll see if I can change it
