### ISSUE TITLE
Remove alumni from OpenStack & servers

### ISSUE THREAD

**Issue by julianpistorius** [az-digitalag/organization#120]
- [x] Remove accounts from Welsch server (any other servers?)
- [x] Remove or disable the user accounts from the `cals` OpenStack project
- [x] Write SOP for how to do this
- [ ] ~~Proposal: Manage access to servers and OpenStack (and as much of the rest of our infrastructure as possible) through some SSO (single sign-on), centrally managed mechanism. We could use GitHub teams for SSO, combined with something like [Teleport](https://github.com/gravitational/teleport).~~

This would be a good opportunity to require 2FA for members of the GitHub organization, and buy everyone [hardware tokens](https://www.yubico.com/products/yubikey-hardware/) while we're at it.

**Comment by julianpistorius** [comment]
@dlebauer & @Chris-Schnaufer can you think of any other servers and accounts we need to check?

**Comment by dlebauer** [comment]
Any other accounts listed on the onboarding wiki (google, github, etc?). 

Regarding SSO, multiple accounts for each service is a big bottleneck - we should discuss separately how we might implement this. So the "Proposal" on the task list can be a separate discussion issue.

What is the priority of this?

**Comment by julianpistorius** [comment]
> Regarding SSO, multiple accounts for each service is a big bottleneck

Not sure what this :arrow_up: means, but can discuss separately:

> What is the priority of this?

Not high.

**Comment by Chris-Schnaufer** [comment]
@julianpistorius @dlebauer Can this be closed?

**Comment by dlebauer** [comment]
TODO 
* [ ] need to remove accounts from Welsch, 
* [ ] add info to offboarding about which accounts to remove

**Comment by julianpistorius** [comment]
Moving this to the current sprint. I'll tidy things up this week.

**Comment by dlebauer** [comment]
* updated offboarding
* on Welsch Chris needs to 

```
for name in kimberlyh tterrazas
do
  sudo userdel $name
  sudo rm -r /home/$name
done
```

Not sure how to manage users in https://tombstone-cloud.cyverse.org/ cso domain

**Comment by julianpistorius** [comment]
Done. Current users:

```
+----------------------------------+----------------+
| ID                               | Name           |
+----------------------------------+----------------+
| 646d62933b064dd880da1dd324c71a51 | csoadmin       |
| 8fc7e134c4084001a21e73d5f1a76266 | schnaufer      |
| d1a17c0edebb456dbdf1e2265049d258 | dlebauer       |
| fab0bcc8dc7a403cad7451dd50d07026 | rbartelme      |
| 0957cd04bf37490fbcc39b842fdd5f83 | admin          |
| c7e0bb85b7fb4b8cbd2ee3f462494d75 | julianp        |
| d3b69b4f04674ed186b7eb0d8c720c4c | kristinariemer |
+----------------------------------+----------------+
```
