### ISSUE TITLE
Create Pecan Vice app

### ISSUE THREAD

**Issue by KristinaRiemer** [az-digitalag/organization#121]

**Comment by KristinaRiemer** [comment]
@julianpistorius would you be interested in helping/leading this?

**Comment by julianpistorius** [comment]
@KristinaRiemer Yes! I can help with this. 

P.S. I'm sorry I just saw this. GitHub notifications are a black hole for me.

**Comment by julianpistorius** [comment]
Duplicate of #93

**Comment by KristinaRiemer** [comment]
I'm closing this in favor of that issue.
