### ISSUE TITLE
Start rough draft of Open Life Science application

### ISSUE THREAD

**Issue by KristinaRiemer** [az-digitalag/organization#129]
This is due on December 8. See [their website](https://openlifesci.org/) for more details. 

- [ ] Determine who else wants to be involved
- [ ] Choose project
- [ ] Attend webinar on November 27 [agenda](https://docs.google.com/document/d/1EIDzZi5mgRiWR7cJQl0up470C87GsbcoTR_6-cs-SeE/edit)
- [ ] Have answers for all application questions

**Comment by KristinaRiemer** [comment]
Past Mozilla projects: https://foundation.mozilla.org/en/opportunity/mozilla-open-leaders/past-rounds/

**Comment by KristinaRiemer** [comment]
Application is here: https://docs.google.com/document/d/167JTkqQ9RlwqLX_az3hn167rXevwvKjr9lHY1phwp9I/edit

**Comment by Chris-Schnaufer** [comment]
Moving checkboxes to follow up issue
