### ISSUE TITLE
Add/update vignette for running BioCro in PEcAn using Welsch

### ISSUE THREAD

**Issue by KristinaRiemer** [az-digitalag/organization#13]

**Comment by KristinaRiemer** [comment]
See PR [here](https://github.com/az-digitalag/model-vignettes/pull/3).

**Comment by Chris-Schnaufer** [comment]
Waiting for Tonantzin to review pull request

**Comment by dlebauer** [comment]
Created a new issue to review PR https://github.com/danforthcenter/sentinel-detection/issues/52

**Comment by dlebauer** [comment]
Created a new issue to review PR https://github.com/danforthcenter/sentinel-detection/issues/52
