### ISSUE TITLE
Investigate Welsch cron job emails

### ISSUE THREAD

**Issue by julianpistorius** [az-digitalag/organization#130]
- [x] Check out what's going on (@julianpistorius)
- [ ] Add ~Julian's~DIAG email address so he can receive cron job failures (CyVerse) ~(@Chris-Schnaufer)~

**Comment by julianpistorius** [comment]
[backups.txt](https://github.com/az-digitalag/organization/files/3870491/backups.txt)

@Chris-Schnaufer It looks like `pg_dump` failed for a while, but now it's working again.

Could you please add my email address to the list of emails so I can receive cron failures?

**Comment by Chris-Schnaufer** [comment]
@julianpistorius You will need CyVerse to do that since it's some kind of distro list. Try starting with Chris Martin?
