### ISSUE TITLE
Submit completed Open Life Science application

### ISSUE THREAD

**Issue by KristinaRiemer** [az-digitalag/organization#132]
Due Dec 8. Discuss w/ David in Florida

**Comment by KristinaRiemer** [comment]
This was submitted on December 8. The completed application is here: https://docs.google.com/document/d/167JTkqQ9RlwqLX_az3hn167rXevwvKjr9lHY1phwp9I/edit#heading=h.wqdyv4ny4d2j. They should announce the results December 20.

**Comment by dlebauer** [comment]
We were accepted and are starting this month. Woo hoo!
