### ISSUE TITLE
Draft Job Ad for DARPA programmer

### ISSUE THREAD

**Issue by dlebauer** [az-digitalag/organization#137]
Not too narrow, but ideally entry to mid level w/ R and HPC skills.

**Comment by KristinaRiemer** [comment]
The Google Doc with the draft of the job ad is here: https://docs.google.com/document/d/1D_hqht_gKeOMk-poE1ki7sYEz8OwBSxwA5wgdpNuJv4/edit

This is based off of the ad from last fall: https://docs.google.com/document/d/1iBtWJEJF6O7b4Yjr8hEc-LCcfBSdzngyqyPc-H7o-ls/edit
