### ISSUE TITLE
Document how to run GWAS and terraref phenotype data in CyVerse

### ISSUE THREAD

**Issue by dlebauer** [az-digitalag/organization#152]
Not to reproduce TASSEL docs (or CyVErse docs) but to walk someone through steps of running this w/ data generated from TERRA REF

Should start with scripts that Emily wrote and end with TASSEL output

goal is for someone to be able to run this w/ different phenotypes or seasons etc

**Comment by rbartelme** [comment]
Closing this issue & removing points, since Kent at OSU is doing the GWAS.
