### ISSUE TITLE
Post notes from Metadata Meeting on 1-17-2020

### ISSUE THREAD

**Issue by MagicMilly** [az-digitalag/organization#153]
Post notes from Metadata / EML Meeting with David and Jeanette on 1-17-2020. Work through tutorials using EML and dataspice packages.

**Comment by MagicMilly** [comment]
Posted notes with request for reviews in pull request #161

**Comment by KristinaRiemer** [comment]
This is waiting on @rbartelme to review before merging the PR.

**Comment by MagicMilly** [comment]
Thank you Jeanette & Ryan for reviewing the notes! PR merged, closing this issue.
