### ISSUE TITLE
Create DIAG community on Cyverse DE

### ISSUE THREAD

**Issue by Sithyphus** [az-digitalag/organization#156]
Create a DIAG community, or group (whichever would better, perhaps just find out what the differences are between), within the Cyverse DE for sharing apps, data, and anything else the discovery environment allows us to do as a community.

**Comment by MagicMilly** [comment]
I created a Team (for DIAG and for the GenoPhenoEnvo Group) because that allows for sharing of private apps and data between collaborators. The Communities appear to just be a space for sharing favorite public apps. 

Everybody has management privileges for now.
