### ISSUE TITLE
Create/Populate Offboarding Protocols on OSF

### ISSUE THREAD

**Issue by Sithyphus** [az-digitalag/organization#157]
Just as the title says, maybe put something in place for exit protocols on the OSF. Not sure how much can be generalized considering it'll usually be specific from person to person but it's worth some thought.

**Comment by KristinaRiemer** [comment]
Offboarding content is on this OSF page: https://osf.io/tzmhp/wiki/Offboarding/

**Comment by dlebauer** [comment]
I've made a few changes; everyone in the group should review and give feedback. Or perhaps we should review as a group.

**Comment by KristinaRiemer** [comment]
This is a good start, we'll have to figure out the exit interview part more specifically.
