### ISSUE TITLE
Move Test DB tutorial to TERRA REF tutorials

### ISSUE THREAD

**Issue by Chris-Schnaufer** [az-digitalag/organization#16]
Next stop for ticket https://github.com/terraref/tutorials/issues/140

* Move the [gist from that ticket](https://gist.github.com/kimberlyh66/935106e35478829b9e844ba5b496784d) to the tutorials repo in the /metadata folder
* Submit as a PR for Kristina and I to review
  * quick comment ... should explain under prerequisites why you need docker and psql.

**Comment by kimberlyh66** [comment]
See pull request https://github.com/terraref/tutorials/pull/143
