### ISSUE TITLE
Manage access to group servers

### ISSUE THREAD

**Issue by julianpistorius** [az-digitalag/organization#160]
Use cases:

- When somebody leaves group
- When somebody changes team within group
- Granting selective super-user access
- Collaborators who come and go
- Temporary access
- Audit successful as well as failed access attempts
- Log commands entered in SSH sessions (optional)

Options:

- <https://github.com/gravitational/teleport> : "Privileged access management for elastic infrastructure."
- <https://www.vaultproject.io/docs/secrets/ssh/> : "The Vault SSH secrets engine provides secure authentication and authorization for access to machines via the SSH protocol. The Vault SSH secrets engine helps manage access to machine infrastructure, providing several ways to issue SSH credentials."
- <https://github.com/jirutka/ssh-ldap-pubkey> : Set up our own LDAP server to manage Unix users, and use this utility to manage public keys through LDAP.
- Something like Ansible or Terraform: Use to manage users, super-user access, SSH keys
- ???

For production applications I advise using immutable infrastructure deployed using something like Nomad.

- <https://www.digitalocean.com/community/tutorials/what-is-immutable-infrastructure>

**Comment by dlebauer** [comment]
what we've been doing is working so far. Fortunately we don't do a lot of offboarding; can be done manually or opened back up when we need to.
