### ISSUE TITLE
OLS weeks 3-4

### ISSUE THREAD

**Issue by KristinaRiemer** [az-digitalag/organization#163]
Week 3: 
- [x] 3 assignments
- [x] Comment on two other projects' issues
- [x] Discuss Open Canvas & Roadmap with Katrin

Week 4: 
- [x] Learn about useful files for an open project during cohort call
- [x] Start creating those
- [ ] Set up meeting with @Chris-Schnaufer to discuss AgPipeline
- [x] Rewrite lay-person vision statement

**Comment by MagicMilly** [comment]
We commented on [Open Science UMontreal](https://github.com/open-life-science/ols-1/issues/4) and the [InterMine Similarity Finder Tool](https://github.com/open-life-science/ols-1/issues/10).

**Comment by KristinaRiemer** [comment]
Templates for the project files are going in [the AgPipeline .github repo](https://github.com/AgPipeline/.github/pulls). We need to finish reviewing this and merge them?
