### ISSUE TITLE
Write and publish FOSS blog post

### ISSUE THREAD

**Issue by MagicMilly** [az-digitalag/organization#169]

**Comment by KristinaRiemer** [comment]
A most excellent idea!

**Comment by dlebauer** [comment]
Draft is here: https://docs.google.com/document/d/1_esn2zog4s1mg4nKI4I5EAn7UFVq8i3N9xHS2bJHy24/edit?usp=sharing

**Comment by MagicMilly** [comment]
Blog post [here](https://datascience.cals.arizona.edu/news/2020/03/foss-2020)
