### ISSUE TITLE
Add mentoring section to OSF pages

### ISSUE THREAD

**Issue by MagicMilly** [az-digitalag/organization#178]
Especially with new hires (despite level of experience), could be helpful to have an official mentorship program in place, where people check in regularly with the same person for a period of time, or have rotating mentors (Kristina mentioned that having somebody to talk to who is _not_ working on the same project could be easier / mentees feel they can speak more freely).

**Comment by KristinaRiemer** [comment]
Added a TBD note about mentoring to [onboarding](https://osf.io/tzmhp/wiki/Onboarding/) and [standups](https://osf.io/tzmhp/wiki/Standups/) OSF pages. We should discuss how to do this as a group.

**Comment by MagicMilly** [comment]
I'm going to work on a draft for this during Writing Hour on 2020-06-05 and send it to @KristinaRiemer and @julianpistorius for editing / review.

**Comment by MagicMilly** [comment]
I created a very rough first draft during my own private Writing Hour. Please share any comments, concerns, or questions! Google doc [here](https://docs.google.com/document/d/1ZyyFrKhdEJSQAUkWLRU05lpa4TFOjzJyqmL3KV1aQic/edit?usp=sharing).

**Comment by julianpistorius** [comment]
Had a quick look at the version of the doc as at 2020-06-05T15:00 and it seems fine.

**Comment by Chris-Schnaufer** [comment]
Create a new issue to publish this

**Comment by MagicMilly** [comment]
Follow-up ticket #231
