### ISSUE TITLE
Automate PSInet processes using service account

### ISSUE THREAD

**Issue by diazrenata** [az-digitalag/organization#1816]
After talking with UITS + Matt:

* we should transfer the google sheets so they are owned by and live in the shared drive
* we may be able to set up a service account and auth using a token (https://gargle.r-lib.org/articles/non-interactive-auth.html#google-compute-engine), but this may be additional layers of unwanted setup ad may not work in our instance, in which case we can stay as we are for now (and assume there will be some work to do if ownership of psinetrcn changes).

* matt says we can do the automated emails from a headless 365 account.

**Comment by KristinaRiemer** [comment]
@diazrenata this is probably not relevant anymore now that PSInet infra has been moved away from UA?

**Comment by diazrenata** [comment]
That's correct!
