### ISSUE TITLE
Find reviewers for tidytacos [JOSS]

### ISSUE THREAD

**Issue by diazrenata** [az-digitalag/organization#1848]

**Comment by KristinaRiemer** [comment]
What is this name though?! ❤️ 🌮

**Comment by diazrenata** [comment]
Isn't it great? 😀 

Keeping a list here:

- https://github.com/david-barnett
- https://github.com/schuyler-smith
- https://github.com/ewallace
- https://github.com/kelly-sovacool

**Comment by diazrenata** [comment]
Done, and review started.
