### ISSUE TITLE
(Attempt to) get rangeland docs ML pipeline running again

### ISSUE THREAD

**Issue by KristinaRiemer** [az-digitalag/organization#1878]
Update [README](https://bitbucket.org/cals-cct/docs-classification-model/src/main/README.md)

**Comment by Aariq** [comment]
Maybe split updating README into a separate issue?

**Comment by KristinaRiemer** [comment]
Cannot figure out what's causing this error in `evaluate_fit` step, and it's happening for all tags: `Error in if (!is.na(resamp_metrics_roc)) { : the condition has length > 1`

**Comment by Aariq** [comment]
What it literally means is that `is.na(resamp_metrics_roc)` returns more than one logical value.  Maybe you want something like `if(!any(is.na(rsamp_metrics_roc)))`? Or maybe `rsamp_metrics_roc` is not what you think it is?
