### ISSUE TITLE
Document instructions on how to make changes to the new website

### ISSUE THREAD

**Issue by MagicMilly** [az-digitalag/organization#188]
- Clone to local machine
- Instructions for creating a branch and for forking your own repo
- How to make changes locally and then create PR for review
- How to stay updated with master / pull changes
- either in README.md or CONTRIBUTING.md

**Comment by KristinaRiemer** [comment]
Include instructions for how to: 
- Add a new person to **People** section
- Add a new blog post to **Posts** section

**Comment by MagicMilly** [comment]
WIP: Have started a [README](https://github.com/MagicMilly/group-website/blob/master/README.md) with instructions on how to get started and stay up to date with changes when working from a forked repo

**Comment by MagicMilly** [comment]
Draft [pull request](https://github.com/az-digitalag/group-website/pull/3) in `group-website` repo

**Comment by MagicMilly** [comment]
PR will be ready for review by end of this Sprint

**Comment by MagicMilly** [comment]
Closing this issue and opened new ticket #202 to 
- [ ] ensure correct function for adding images to blog posts is included in the instructions
- [ ] link to general git / github workflow on OSF and only include git instructions specific to this repo (if any)
- [ ] review git / github workflow instructions on OSF and provide more detail if needed

Instructions for adding to the People and blog post sections (with no images) included in the WIP [PR](https://github.com/az-digitalag/group-website/pull/3)
