### ISSUE TITLE
Compile daily weather data for Seasons 4 and 6 from AzMET

### ISSUE THREAD

**Issue by dlebauer** [az-digitalag/organization#193]
These are here 
[azmet.zip](https://github.com/az-digitalag/organization/files/4451951/azmet.zip). Next step is to put them alongside the other data ...

**Comment by KristinaRiemer** [comment]
Included in the ARDN repo pull request as [a commit](https://github.com/az-digitalag/ardn-terra-ref/pull/1/commits/d3090d3264e72e5bf23d26a1cf2edfbc28721ace).
