### ISSUE TITLE
Identify missing or broken BrAPI endpoints and create examples of what the data should like following BrAPI specification

### ISSUE THREAD

**Issue by dlebauer** [az-digitalag/organization#194]

**Comment by KristinaRiemer** [comment]
This should accompany [the issue about getting endpoints](https://github.com/az-digitalag/organization/issues/189), right?

**Comment by dlebauer** [comment]
yes - this for any errors or omissions found in that process. First step before fixing the API is to mock up what the content will be.

**Comment by KristinaRiemer** [comment]
We did this during the hackathon.
