### ISSUE TITLE
Prepare Presentation for Quarterly Meeting

### ISSUE THREAD

**Issue by MagicMilly** [az-digitalag/organization#196]
Presentations should include

- Q1: progress, what went well, major accomplishments, etc. 
- Q2: new OKR's, goals

- [x] Chris
- [x] David
- [x] Emily
- [x] Julian
- [x] Kristina
- [x] Ryan

**Comment by KristinaRiemer** [comment]
We all completed our presentations, and did a great job presenting them! Links to all presentations are in [the agenda notes](https://hackmd.io/EuCt5lbASCWpCLUT6Zdbtw?view).
