### ISSUE TITLE
Improve People section of website

### ISSUE THREAD

**Issue by KristinaRiemer** [az-digitalag/organization#198]
- [x] Add links to each person's page for GitHub, Linkedin, website, etc. 
- [x] Make homepage cards same size

**Comment by KristinaRiemer** [comment]
Taken care of in [PR #9](https://github.com/az-digitalag/group-website/pull/9) with switch from projects widget to people widget.

**Comment by Chris-Schnaufer** [comment]
@dlebauer What milestone was this for? Can you also change it's pipeline to reflect its status?

**Comment by KristinaRiemer** [comment]
Like with #210, I was waiting until the PR linked above was closed to close this issue. Closing now.
