### ISSUE TITLE
Create OSF page for Ag data group

### ISSUE THREAD

**Issue by dlebauer** [az-digitalag/organization#2]
* Place for group protocols, including onboarding document
* Create subproject for metadata upload 

replaces https://github.com/terraref/tutorials/issues/133

**Comment by kimberlyh66** [comment]
@dlebauer @Chris-Schnaufer @KristinaRiemer OSF for Ag data group has been created. Everyone needs to create an OSF account in order to make contributions.

**Comment by KristinaRiemer** [comment]
I have an account. Can you provide the link to the group?

**Comment by kimberlyh66** [comment]
Sure. Here is the link: https://osf.io/emq9s/

**Comment by kimberlyh66** [comment]
I will need to make you a contributor before you can view the page.
