### ISSUE TITLE
Identify 3 Potential Research Projects for Collaboration within CALS

### ISSUE THREAD

**Issue by MagicMilly** [az-digitalag/organization#200]
In support of our mission to `provide scientists and engineers with open software, data, and computing that will allow more efficient discovery and invention`, identify 3 potential research projects within UA CALS that could benefit from our team's work.

**Comment by MagicMilly** [comment]
Have already met with Susan Malusa and Julian to discuss her trap cam [app](https://github.com/CulverLab/sparcd)
- [Notes](https://hackmd.io/@eywX1MatRnyBtYFBB3Gqwg/B1InCX0_8) from that meeting

Meeting with Susan, Julian, and potential collaborators from National Park Service today.

**TODO**
- [ ] Schedule meeting with [Austin Rutherford](https://datascience.arizona.edu/person/austin-rutherford) - DS Ambassador for CALS - for me and David to discuss projects that could use our help
- [ ] Write short proposals for at least 3 potential projects

**Comment by MagicMilly** [comment]
David and I are meeting with Austin on Wednesday, April 29, 2020 at 1200.

**Comment by MagicMilly** [comment]
Shared the google doc with proposals with @dlebauer and @KristinaRiemer during Writing Hour for review.

**Comment by dlebauer** [comment]
I've updated notes on discussions with Sue. 

@MagicMilly If you can link to the short proposals then we can close the issue.

**Comment by MagicMilly** [comment]
Link to [proposals](https://docs.google.com/document/d/14hbua487eVh_x3PwCWI1ZXtpRUfvoiWtmXVliIqW_xE/edit?usp=sharing)
