### ISSUE TITLE
Provide SQLite of image information

### ISSUE THREAD

**Issue by Chris-Schnaufer** [az-digitalag/organization#2063]
**Task to do**
Create a SQLite file for all the images and contains:

- Unique DB Image ID
- Collection/container ID
- Upload path (corresponding to date specific upload in SPARCd)
- Remaining path to image (if there is one)
- Image name
- Image hash value
- Image stored species names and counts
- Image stored location name and lat-lon
- CamTrap species names and counts
- CamTrap location name and lat-lon
- Duplicate image IDs

**Reason**
Provide a means of finding images that have certain attributes

**Result**
There's a SQLite query-able database

**Comment by KristinaRiemer** [comment]
@Chris-Schnaufer does this need to be closed / moved / edited?

**Comment by Chris-Schnaufer** [comment]
Not yet. Thanks

**Comment by Chris-Schnaufer** [comment]
Database has been generated and works as expected
