### ISSUE TITLE
Define, create, and add additional figures for Drone paper

### ISSUE THREAD

**Issue by dlebauer** [az-digitalag/organization#208]

**Comment by dlebauer** [comment]
* [ ] workflow overview
* [ ] example analyses

**Comment by Chris-Schnaufer** [comment]
Let me know how I can help with the figures

**Comment by dlebauer** [comment]
@Chris-Schnaufer I  know this is pretty late in the game, but it would be great (not required) but if you already have any of the following, it would be great to have results from one of the use cases (ideally G2F since data are already published!) 
* raw image, 
* one field mosaic w/ plots, 
* masked image 
* image clipped to plot
* csv file.

**Comment by Chris-Schnaufer** [comment]
Hello David. As you know, we unfortunately don't have the Ground Control point files that are needed for accurate geographic plot clipping at this time. So we only have raw images and ortho mosaics (that are not correctly geo referenced).
