### ISSUE TITLE
Drone Pipeline Overview Outline / etc 

### ISSUE THREAD

**Issue by dlebauer** [az-digitalag/organization#21]
Just got a call from a collaborator who is interested in seeing the drone pipeline. 

I think the osf wiki is a good place to start, but we also need something of a walk through demonstration - a presentation with screenshots that can be updated as the pipeline is updated, and that can be used to demonstrate, e.g. in a video conference. 

Should include:

- what we currently have
- required inputs
- outputs
- how to add a new plot level raster to phenotype extractor

**Comment by Chris-Schnaufer** [comment]
The presentation is available at https://drive.google.com/open?id=1CuZlZ4zAvyi6_XP7JnZL0UNifAnuX0JResEbXAj_EMA

**Comment by dlebauer** [comment]
Looks like a great start. Definitely has most of the critical content in place; it will probably be worthwhile to go through this with friendly users in the group to see if it provides them with what they need to take it from here.

Also, I started very roughly sketching a few additional slides that I think would be helpful:

* a motivating overview: what is the problem you are solving? who is the audience?
* highest level view of what will happen highest level overview  
* a slide w/ references / links to relevant resources including osf, github, links to jupyter notebook

Finally, in the instruction slides, provide actual commands (at a minimum, screenshots w/ links to the jupyter notebook).
