### ISSUE TITLE
In the People section, correct "Related" list

### ISSUE THREAD

**Issue by MagicMilly** [az-digitalag/organization#210]
David & Kristina only link to each other, while other team members link to everybody

How it should look
<img width="223" alt="Screen Shot 2020-05-01 at 11 15 29 AM" src="https://user-images.githubusercontent.com/34486154/80830052-27ad0c00-8b9d-11ea-8a57-55fbd5298132.png">

How David's looks
<img width="213" alt="Screen Shot 2020-05-01 at 11 15 39 AM" src="https://user-images.githubusercontent.com/34486154/80830103-3e536300-8b9d-11ea-99db-1281eed43c30.png">

**Comment by KristinaRiemer** [comment]
Taken care of in [PR #9](https://github.com/az-digitalag/group-website/pull/9) with switch from projects widget to people widget.

**Comment by Chris-Schnaufer** [comment]
@KristinaRiemer Can you fill out the missing information on this issue and change its Pipeline to reflect its status?

**Comment by KristinaRiemer** [comment]
That pull request has been merged, so I'm closing this issue now.
