### ISSUE TITLE
submit travel authorization

### ISSUE THREAD

**Issue by Aariq** [az-digitalag/organization#2113]
- [x] do training on new travel authorization
- [x] decide on travel dates
- [x] fill out travel authorization form
- [ ] register
- [ ] book hotel

**Comment by Aariq** [comment]
Can't log in to travel authorization form

**Comment by KristinaRiemer** [comment]
@Aariq I'm trying to figure out how to log into the website, will get back to you!

**Comment by KristinaRiemer** [comment]
Correct link: https://financialservices.arizona.edu/travel

**Comment by Aariq** [comment]
I'll create a follow-up issue for registering and booking travel and lodging for July
