### ISSUE TITLE
[US-RSE] register, book hotel and rental car

### ISSUE THREAD

**Issue by Aariq** [az-digitalag/organization#2127]
- [x] Fix travel auth form to include all hotel nights and registration fee (https://financialservices.arizona.edu/travel)
- [x] Rent car
- [ ] Book additional days (personal)

**Comment by Aariq** [comment]
@KristinaRiemer Do we need to do this together over Zoom?  Can you just share the p-card with stache?  How do you want to proceed?

**Comment by KristinaRiemer** [comment]
I'm the only person who can use my p-card. So either I can purchase things for you, or if you prefer to do it yourself you could use Matt's CCT card?

**Comment by Aariq** [comment]
Ok, I'll try to get as organized as I can so you can book stuff on my behalf

**Comment by Aariq** [comment]
Closing and I'll book the hotel on my own time
