### ISSUE TITLE
Start planning Fall Workshop Series 2024

### ISSUE THREAD

**Issue by Aariq** [az-digitalag/organization#2135]
- [x] Schedule meeting to get going.
- [x] Decide on dates and schedule
- [x] Update application form (https://docs.google.com/forms/d/10BJz1FO-SwbnNn_it0668S_8j2566Ic8VW82C-H_ulE/edit)
- [x] Create event on website
- [x] Review curriculum and notes from last year
- [ ] Advertise (the usual places)

**Comment by Aariq** [comment]
2023 course materials: https://cct-datascience.github.io/repro-data-sci/
2023 course materials source: https://github.com/cct-datascience/repro-data-sci
2023 course application form: https://docs.google.com/forms/d/18VkmxPoX2QUeu9vB3hxizMhxcqWxDIJrtvnSVjxVGQ4/edit
2023 retrospective notes: https://docs.google.com/document/d/1-_WZhgp7ip0-Y3XclceAi-4CPLmiggZnk65dxzYIoWo/edit#heading=h.nt6nousdfma7

**Comment by Aariq** [comment]
The only piece I can't find/remember where it lives is the quarto doc to wrangle applications to a readable format.

**Comment by diazrenata** [comment]
> The only piece I can't find/remember where it lives is the quarto doc to wrangle applications to a readable format.

Didn't you make it a blog post on your blog?

**Comment by Aariq** [comment]
11-1 tuesdays and thursdays beginning September 3
Tuesday October 8th—no curriculum planned, drop-in session
Thursday October 10th is reproducibility colloquium (no week off)

**Comment by Aariq** [comment]
Just realized we're not having outreach hour this week and we'll all be out next monday.  I can make a checklist in the outreach hour hackmd of places to advertise
