### ISSUE TITLE
Take group effectiveness survey

### ISSUE THREAD

**Issue by KristinaRiemer** [az-digitalag/organization#2161]

**Comment by Aariq** [comment]
https://forms.gle/b1aBMJnmDkbZRcPKA

**Comment by Aariq** [comment]
I'm assuming we all did this, so I'm going to close this issue

**Comment by KristinaRiemer** [comment]
Looks like everyone did do this! I think this issue is publicly viewable, so we might want to remove the link to the survey cause any random person could take it?
