### ISSUE TITLE
Second round of advertising for Fall Reproducibility Series

### ISSUE THREAD

**Issue by diazrenata** [az-digitalag/organization#2184]

**Comment by Aariq** [comment]
Need some text for "There's still spots left....apply by Monday Aug 26th"

**Comment by diazrenata** [comment]
(Maybe in bold) "Applications are still open! Please send in your application by Monday, August 26th for participation in this year's workshop." perhaps?

Edit - specifically avoiding saying anything about spots being still open, because if we send out rejection emails saying that we couldn't accept everyone, that could be some slightly awkward messaging to the recipients of those emails.

**Comment by Aariq** [comment]
We could hold off on sending emails to those not accepted perhaps?

**Comment by diazrenata** [comment]
I think we decided not to do any more advertising?

**Comment by KristinaRiemer** [comment]
Yup!

**Comment by Chris-Schnaufer** [comment]
Decided no work was needed
