### ISSUE TITLE
Get all model vignettes so rendered .md in repo

### ISSUE THREAD

**Issue by KristinaRiemer** [az-digitalag/organization#22]
- [x] CLM params
- [x] BioCro in PEcAn
- [x] ED2 in PEcAn
- [x] BioCro model

**Comment by KristinaRiemer** [comment]
Done for CLM params (PR [here](https://github.com/az-digitalag/model-vignettes/pull/5)) and BioCro model (PR [here](https://github.com/az-digitalag/model-vignettes/pull/6)).

**Comment by KristinaRiemer** [comment]
Workflow: 
1. Create .Rmd that has `output: github_document` in the YML header
2. Knit .Rmd, which will generate a .md
3. Commit the .Rmd, .md, and any extra files needed to generate it
4. The .md will be formatted nicely for people to look at it the GH repo, and the .Rmd will provide that raw version

**Comment by KristinaRiemer** [comment]
The final PR is https://github.com/az-digitalag/model-vignettes/pull/7, but I already merged it. Should be able to look at all the files in the main repo.

**Comment by KristinaRiemer** [comment]
@kimberlyh66 would you like to review this? All that needs to be done is that you understand the workflow for each of the four vignettes, and that the .md files look okay in the browser for each of them. For example, the BioCro runs vignette [here](https://github.com/az-digitalag/model-vignettes/blob/master/BioCro/biocro_in_pecan.md).

**Comment by kimberlyh66** [comment]
@KristinaRiemer Sure I will review

**Comment by KristinaRiemer** [comment]
Thanks @kimberlyh66!

**Comment by kimberlyh66** [comment]
@KristinaRiemer all four vignettes look good! The workflow is clear and the .md files look nice in the browser. Is there an associated pull request to add my review?

**Comment by KristinaRiemer** [comment]
Great! Thanks for looking at that, @kimberlyh66. I did merge the PR in already so the .md files could be viewed. But for the sake of record keeping, I just added you as a reviewer to that PR, if you want approve it.
