### ISSUE TITLE
Update ED2 on HPC Vignette

### ISSUE THREAD

**Issue by dlebauer** [az-digitalag/organization#220]
* [ ] update the [ED2 on HPC vignette](https://github.com/az-digitalag/model-vignettes/blob/master/ED2/ED2-on-hpc-doc.md) with commands from https://github.com/danforthcenter/sentinel-detection/issues/122.  

Julian's notes and progress: <https://hackmd.io/@julianp-diag/H12YFAwSv>

**Comment by julianpistorius** [comment]
@dlebauer Is this a good candidate for Sprint 40?

**Comment by dlebauer** [comment]
yes

**Comment by julianpistorius** [comment]
## ED2 meeting with @dlebauer 

- Instructions for PEcAn web UI don't work anymore
    - Will not let me edit the config
    - I just killed the process instead
- David helped me find the files I need
- Idea: Use mounting paths in Singularity so we don't have to change input files
    - E.g. `/home/carya/*`

### Next steps

- Copy `/home/carya/output/PEcAn_99000000006` to HPC in my home directory
    - Optional:
        - `/home/carya/output/PEcAn_99000000006/out`
    - Run Singularity bind mounting `~/PEcAn_99000000006` in my home directory to `/home/carya/output/PEcAn_99000000006` in the container
- Start trying to run the container, and update the docs below as I go
- Update <https://github.com/az-digitalag/model-vignettes/blob/master/ED2/ED2-on-hpc-doc.md>
    - Replace `*.ed.r82` with something like `ed2-2.2.0` (as in the Docker image)
    - Note: Docker image has changed to - <https://hub.docker.com/r/pecan/model-ed2-2.2.0>
    - Goal: Keep track of the difference in the input and run scripts between running on a VM and running on Singularity on HPC
        - `/home/carya/sites/ebifarm/ED_MET_DRIVER_HEADER`
        - `/home/carya/output/PEcAn_99000000006/run/99000000005/job.sh`
        - `/home/carya/output/PEcAn_99000000006/run/99000000005/config.xml`
        - See `/home/carya/output/PEcAn_99000000006/run/99000000005/ED2IN` for all the required files
    - Run ED2 in Singularity with the ED2IN file generated by VM, see what fails (if anything)
        - David says I might have to look at the two ED2IN files: <https://github.com/PecanProject/pecan/tree/develop/models/ed/inst>
- STOP HERE and talk to Kristina & David

### Later

- Update PEcAn in virtual machine from GitHub (develop branch)
    - `git pull`
    - `make`
- Then run the web interface steps with latest PEcAn develop branch
    - Goal: ???

**Comment by julianpistorius** [comment]
@dlebauer & @KristinaRiemer I think I've reached the point above:

> STOP HERE and talk to Kristina & David

## Progress

On Mac, tar up the directory from the VM and upload to HPC:

```bash
tar cvzf PEcAn_99000000006.tar.gz PEcAn_99000000006
scp PEcAn_99000000006.tar.gz sftp-hpc:
```

On HPC:

```bash
# 1. Stage the data

mkdir -p ~/pecan
mv ~/PEcAn_99000000006.tar.gz ~/pecan

cd ~/pecan

rm -rf inputs
mkdir -p inputs
curl -o inputs.tgz http://isda.ncsa.illinois.edu/~kooper/EBI/inputs.tgz
tar xzf inputs.tgz -C inputs

rm -rf sites
curl -o sites.tgz http://isda.ncsa.illinois.edu/~kooper/EBI/sites.tgz
tar zxf sites.tgz
sed -i -e "s#/home/kooper/Projects/EBI#/home/carya#" sites/*/ED_MET_DRIVER_HEADER

cd ~/pecan
mkdir -p output
tar xfz PEcAn_99000000006.tar.gz -C output

# 2. Pull container image

module load singularity
singularity pull pecan-model-ed2.sif docker://pecan/model-ed2-2.2.0:develop

# 3. Run container image

singularity run -B ~/pecan/sites:/home/carya/sites \
-B ~/pecan/inputs/ed_inputs:/home/carya/ed_inputs \
-B ~/pecan/output:/home/carya/output \
pecan-model-ed2.sif /bin/bash

# Should now see prompt: Singularity>

# 4. Fix job.sh to run the right model

cd /home/carya/output/PEcAn_99000000006/run/99000000005

# Change model binary from ed2.git to ed.2.2.0
sed -i -e "s#/usr/local/bin/ed2.git#/usr/local/bin/ed.2.2.0#" job.sh
sed -i -e 's#"/usr/local/bin/ed.2.2.0" ""#"/usr/local/bin/ed.2.2.0" "-s"#' job.sh

# 5. Run job.sh

./job.sh

# 6. Look at log file

cat /home/carya/output/PEcAn_99000000006/out/99000000005/logfile.txt | more
```

Should see log file:

```
Logging on 2020/08/14_23:27:25
+---------------- MPI parallel info: --------------------+
+  - Machnum  =      0
+  - Machsize =      1
+---------------- OMP parallel info: --------------------+
+  - thread  use:       1
+  - threads max:       1
+  - cpu     use:       1
+  - cpus    max:       1
+  Note: Max vals are for node, not sockets.
+--------------------------------------------------------+
Reading namelist information
Copying namelist

------------------------------------------------------
>>>>  opspec_times  error! in your namelist!
    ---> Reason:      MONTH_YRSTEP must be a a valid calendar month (1-12), and yours is set to   -999...
------------------------------------------------------

 -----------ED_OPSPEC_TIMES ------------------------
 Fatal errors:     1
 ---------------------------------------------------
::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::

--------------------------------------------------------------
                     !!! FATAL ERROR !!!
--------------------------------------------------------------
    ---> File:        ed_opspec.f90
    ---> Subroutine:  ed_opspec_times
    ---> Reason:      Fatal errors at namelist - Time settings
--------------------------------------------------------------
 ED execution halts (see previous error message)...
--------------------------------------------------------------
STOP fatal_error
ERROR IN MODEL RUN
Logfile is located at '/home/carya/output//PEcAn_99000000006/out/99000000005/logfile.txt'
************************************************* End Log 2020/08/14_23:27:25
```

**Comment by julianpistorius** [comment]
Tried to update PEcAn in the VirtualBox VM to both master and develop, and rebuild with `make`, but got build errors.

Instead of spending more time on that I will use the latest Docker Compose setup and create a run directory from that.

**Comment by julianpistorius** [comment]
Got the HPC execution working (see [notes](https://hackmd.io/@julianp-diag/H12YFAwSv#2020-09-25)) but I need to summarize my notes into the vignette.

**Comment by julianpistorius** [comment]
Follow-up: https://github.com/az-digitalag/organization/issues/328
