### ISSUE TITLE
Decide on fall workshop series applications

### ISSUE THREAD

**Issue by diazrenata** [az-digitalag/organization#2200]

**Comment by Aariq** [comment]
Follow-up tasks:

- [x] Find email templates used from last year (@Aariq) (in PR https://github.com/cct-datascience/repro-data-sci/pull/22)
- [x] Email accepted applicants (@Aariq)
- [x] Email Rachel Gildersleeve (@Aariq)
- [ ] Email applicants that don't meet minimum qualifications (do this later??)
