### ISSUE TITLE
Create plan for curriculum & funding

### ISSUE THREAD

**Issue by KristinaRiemer** [az-digitalag/organization#222]
Followup on meeting May 22 w/ @dlebauer. Include action items.

**Comment by KristinaRiemer** [comment]
[HackMD for all teaching-related notes](https://hackmd.io/3mx3j-lVSLaQiZAzbaxX0A)

TODO: 
- [ ] Meet with Bonnie Hurowitz about BSE needs
- [ ] Meet with Katy Prudic about SNRE teaching
- [ ] Review prior curriculums to be possibly modified to UA needs

**Comment by dlebauer** [comment]
superseded by monthly workshops
