### ISSUE TITLE
Publish OLS blog post

### ISSUE THREAD

**Issue by KristinaRiemer** [az-digitalag/organization#223]

**Comment by KristinaRiemer** [comment]
Have created the initial post with an outline, see [the pull request](https://openlifesci.org/). Still need to write the first draft, edit, and publish on the old website.

**Comment by KristinaRiemer** [comment]
There is a finished draft in the PR. Looking for feedback and improvements from @dlebauer and @MagicMilly now.

**Comment by Chris-Schnaufer** [comment]
Create new issue for publishing post
