### ISSUE TITLE
Consult with Chris re: forestTIME

### ISSUE THREAD

**Issue by diazrenata** [az-digitalag/organization#2266]

**Comment by Chris-Schnaufer** [comment]
@diazrenata When would a good time be for this? I'm available Mon & Wed all day and Tues morning (outside of the usual meetings)

**Comment by diazrenata** [comment]
@Chris-Schnaufer Apologies! I'm not sure if there will be time for this this week. The database is still very in-development. I do think it would be very helpful for whoever picks it up after me to chat with you about the database design when it is farther along, if that's a possibility!

**Comment by Chris-Schnaufer** [comment]
Thanks. That works for me
