### ISSUE TITLE
Set up & have wrap-up meeting with Dave Moore

### ISSUE THREAD

**Issue by Aariq** [az-digitalag/organization#2287]
Get a meeting on the calendar for after USRSE to wrap up current phase of work and discuss timing of next steps

**Comment by KristinaRiemer** [comment]
I think this hasn't been scheduled yet, right @Aariq?

**Comment by KristinaRiemer** [comment]
I will be setting this up with Dave

**Comment by Aariq** [comment]
https://docs.google.com/document/d/1BmLeXmFbBvJ8MYP8DHbxab2S_7iZVeoHINuAgrHvhaI/edit?tab=t.0
