### ISSUE TITLE
Review updated flyer text field

### ISSUE THREAD

**Issue by Chris-Schnaufer** [az-digitalag/organization#2317]
**Task to do**
Review the new text used in the flyer and approve final wording

**Reason**
At least one of the sentences needs work

**Result**
A new flyer is ready (or at least the text is)

** Original Wording **
Drop-in hours: Free help with your research projects and answers to your programming questions
Incubator: Out experience and know-how to help with your research projects (uncredited? ghost?)
Discover: Check out the many ways we can assist you and add value to your research

URL: https://drive.google.com/file/d/1NOAbg0YjoU9J4kAyEnVzRXC6mnS7Ag5V/view?usp=drive_link

**Comment by Aariq** [comment]
For incubator maybe something like "Pre-funded collaboration with our expert scientific programmers"
