### ISSUE TITLE
Update Sparcd docs for JOSS submission

### ISSUE THREAD

**Issue by KristinaRiemer** [az-digitalag/organization#2323]
- [x] Add details for how to create new Sparcd instance to repo README
- [x] Make sure screenshots are up to date
- [x] Link to Sparcd download page from README (https://github.com/CulverLab/sparcd)
- [x] Update Sparcd download page (Java version, adding a second Mac button for two types of Macs) (see [page](https://www.wildcatresearch.arizona.edu/downloadsparcd))

**Comment by Chris-Schnaufer** [comment]
Updated the README.md file:
- corrected links to point to SPARCd repo
- updated for Java21
- Updated file name text in README to be more correct. For example, file names start with `sparcd-` and the text now reflects this

**Comment by Chris-Schnaufer** [comment]
Added instructions and optional manual upload settings files

https://github.com/CulverLab/sparcd/tree/multiple-root-buckets
