### ISSUE TITLE
Prep for Q2/Q3 meeting

### ISSUE THREAD

**Issue by KristinaRiemer** [az-digitalag/organization#240]
Meeting is happening July 8, 2020. 

- [x] Notes on accomplishments/challenges of Q2 and plans for Q3
- [x] Draft OKRs
- [x] Create presentation
- [x] Contribute to meeting schedule

**Comment by KristinaRiemer** [comment]
- [ ] Notes on accomplishments/challenges of Q2 and plans for Q3
- [ ] Draft OKRs
- [ ] Create presentation
- [ ] Contribute to meeting schedule

**Comment by MagicMilly** [comment]
- [x] Notes on accomplishments/challenges of Q2 and plans for Q3
- [ ] Draft OKRs
- [ ] Create presentation
- [ ] Contribute to meeting schedule
