### ISSUE TITLE
Identify purpose & audience for CS&S event

### ISSUE THREAD

**Issue by KristinaRiemer** [az-digitalag/organization#244]
We'll host an event in 2021, submitting an application for [this funding source](https://eventfund.codeforscience.org/). 

- [x] Attend informational webinar
    - [Slides](https://docs.google.com/presentation/d/1wLMAFNo161IzfxXt3Ln1tbxWRh8d-Mn29c3D397Zj5M/edit#slide=id.g8af4ce24ec_0_86)
- [x] Brainstorm ideas
- [x] Narrow down focus for event audience, purpose, format
- [x] Meet Thursday 7/16 at 1200 AZ time

[Notes](https://hackmd.io/FqgN55s7RLuQiT3n3q8o4g?edit)

**Comment by MagicMilly** [comment]
More virtual events on. . . virtual events

- CSCCE Community Call on July 22
- CarpentryCon@Home breakout session on August 5

**Comment by MagicMilly** [comment]
We have narrowed our our first idea down to a younger audience to "support the development of diverse leaders" in data science. We'll be contacting a middle school teacher who leads a local Girls Who Code chapter on Friday 7/17. Follow-up ticket #250
