### ISSUE TITLE
Create first draft of CS&S event fund application

### ISSUE THREAD

**Issue by KristinaRiemer** [az-digitalag/organization#250]
Should have complete draft of application and know when it needs to be submitted to UA. Due on August 25.

**Comment by MagicMilly** [comment]
This may need to be in another ticket, but I wanted to record it somewhere:

Current Steps
- [ ] Reach out to Larissa by e-mail
- [ ] Hopefully schedule a Zoom chat to discuss event 🤞

**Comment by MagicMilly** [comment]
Zoom chat with Larissa will be on Monday 7/20 at 12 pm AZ time

**Comment by MagicMilly** [comment]
- [ ] Send follow-up email to Larissa by Friday 7/24 with more specific questions

**Comment by MagicMilly** [comment]
Unsure if we are moving forward with this application at this time. If so, next steps will be added to ticket #258
