### ISSUE TITLE
Updates to TERRA REF SQLite databases

### ISSUE THREAD

**Issue by dlebauer** [az-digitalag/organization#254]
* [ ] filepaths can be truncated to start at season-4 and season-6 to be consistent w/ organization at #terra-public endpoing
* [ ] timestamps in filenames are inconsistent with start_date and end_date fields
   * where did start_date and finish_date come from? is this an error in underlying data?
   * more accurate to use timestamp derived from filename?
* [ ] weather data has large gaps in it so ... in some cases the file timestamp can be days different from the weather time stamp. If time difference is > 10 minutes, set to NULL

**Comment by Chris-Schnaufer** [comment]
The point estimation is due to the following requiring re-generation of the SQLite databases:
>  If time difference is > 10 minutes, set to NULL

Investigation the other checkboxes in the issue body may also require regenerating the SQLite databases

**Comment by Chris-Schnaufer** [comment]
Closing as no longer needed
