### ISSUE TITLE
Create MVP of new group website part 1

### ISSUE THREAD

**Issue by KristinaRiemer** [az-digitalag/organization#261]
We'll be doing a hackathon on Aug 5 to accomplish this. To prepare, we need to review/revise [the hackathon plan](https://hackmd.io/7buTmzT8THaClfKOSx6nqQ) and determine who wants to participate for which parts of the day.

**Comment by MagicMilly** [comment]
As a resource, this [site](https://publish.twitter.com/#) will generate the code needed to embed anything twitter-related on your website, including follow buttons, feeds, and even weird things like a list of everything you've ever liked! (not so sure about that last one. . .)

**Comment by KristinaRiemer** [comment]
We've made substantial progress on all components of the website, both during and after the hackathon. See the notes in the plan. All of the pull requests need to be merged, including dealing with conflicts, and follow up pull requests written.
