### ISSUE TITLE
Check on website colors after PRs from hackathon are merged

### ISSUE THREAD

**Issue by Chris-Schnaufer** [az-digitalag/organization#262]
This issue is a result of comment: https://github.com/az-digitalag/group-website/pull/12#pullrequestreview-463526767

Once the PR's are merged, the color scheme needs to be looked at to determine if anything needs to be changed:
Main PR affecting the site: https://github.com/az-digitalag/group-website/pull/11
Other PRs:
* https://github.com/az-digitalag/group-website/pull/8
* https://github.com/az-digitalag/group-website/pull/9
* https://github.com/az-digitalag/group-website/pull/10
* https://github.com/az-digitalag/group-website/pull/12

There may be other PRs or changes that the PR #11 will impact.

**Comment by dlebauer** [comment]
all of the PRs have been merged - unclear what specific action items are here

**Comment by Chris-Schnaufer** [comment]
@dlebauer: Look at the web site color scheme for consistency to make one of the following determinations, followed by the action:
1. The colors look good: add a comment here and move this issue along
2. The colors have problems: add a comment here, write a new issue* to resolve the problems, move this issue along

* Depending upon the problems found, if any, writing an issue may not be necessary; or, any minor changes can be made and documented here

**Comment by dlebauer** [comment]
when we discuss Friday, lets also look at the UA branding 
* colors https://digital.arizona.edu/ua-bootstrap/colors.html

**Comment by KristinaRiemer** [comment]
So the projects and services sections have the wrong color scheme for the rest of the website's now, see screenshots below. 
![Screen Shot 2020-08-28 at 11.17.23 AM.png](https://images.zenhubusercontent.com/5c38e1da82e03870988b36b1/e6ae8100-097d-46f1-933c-e8cdefa00cd4)
![Screen Shot 2020-08-28 at 11.17.38 AM.png](https://images.zenhubusercontent.com/5c38e1da82e03870988b36b1/250644cc-0f76-467b-bf4a-f81134d7c788)

I don't know quite know how to fix that. I think the headers on those sections would need to be changed in [slider-header.html](https://github.com/az-digitalag/group-website/blob/master/layouts/partials/widgets/slider-header.html) and maybe `overlay_color` in the projects.md and services.md? It doesn't seem like it will be as simple as just using the `ua_font_set` thingy like [Julian did for the rest of the website](https://github.com/az-digitalag/group-website/pull/11/files), but I don't know enough about websites to know for sure. @julianpistorius @Chris-Schnaufer 

I did make it so [light mode is the only option](https://github.com/az-digitalag/group-website/pull/15) now though.

**Comment by Chris-Schnaufer** [comment]
Thanks @KristinaRiemer for looking into this. I will add it to my sprint 42

**Comment by Chris-Schnaufer** [comment]
https://github.com/az-digitalag/group-website/pull/17
