### ISSUE TITLE
Review font specification for slider-header widget in Organization website

### ISSUE THREAD

**Issue by Chris-Schnaufer** [az-digitalag/organization#263]
The change to UA fonts might cause the slider-header widget to look different than the rest of the site. This is due to the widget specifying the font to use: `font-family:Montserrat,sans-serif;` at https://github.com/az-digitalag/group-website/blob/c3728b6d8ccbd00319a693467c8021e643b28ddd/layouts/partials/widgets/slider-header.html#L1

Once https://github.com/az-digitalag/group-website/pull/11 is merged, the slider-header widget should be reviewed and changed is necessary

**Comment by dlebauer** [comment]
https://github.com/az-digitalag/group-website/pull/11 has been merged; this is ready for review

**Comment by Chris-Schnaufer** [comment]
@dlebauer It's not clear from the state of this issue as to who should work on this, or when

**Comment by Chris-Schnaufer** [comment]
@dlebauer Can this be closed?

**Comment by dlebauer** [comment]
closed by https://github.com/az-digitalag/group-website/pull/11
