### ISSUE TITLE
David list of tickets to review

### ISSUE THREAD

**Issue by Chris-Schnaufer** [az-digitalag/organization#27]

**Comment by dlebauer** [comment]
I finished a few reviews but still need to do:

* [ ] github.com/terraref/drone-pipeline/issues/29 data required to put plot boundaries in BETYdb

**Comment by dlebauer** [comment]
I'm closing this issue because it isn't as useful as I had anticipated! I started trying to be more attentive to the review column, and will keep the 5 points because of effort spent on other issues; will look at bookdown issue next sprint.
