### ISSUE TITLE
I would like UA header on website, and official UA logo

### ISSUE THREAD

**Issue by dlebauer** [az-digitalag/organization#273]
For header: See https://digital.arizona.edu/ua-bootstrap/interior-example.html

![image.png](https://images.zenhubusercontent.com/583f321cb9dc3c622022c169/301124d1-cb34-4271-b034-bc45074a3d89)

I think adding something like 

```
  <!--   ++++++++++++++ Place inside body tag ++++++++++++++   -->
  <header id="region_header_ua" class="l-arizona-header bg-red">
    <section class="container l-container">
      <div class="row">
        <a href="http://www.arizona.edu" title="The University of Arizona homepage" class="arizona-logo">
           <img alt="The University of Arizona Wordmark Line Logo White" src="https://cdn.uadigital.arizona.edu/logos/v1.0.0/ua_wordmark_line_logo_white_rgb.min.svg" class="arizona-line-logo">
        </a>
       </div>
     </section>
  </header>
```

will be a good start.

For logo, we can use this one

![UA_CALS_Comm CyberTech_ALTERNATE](https://user-images.githubusercontent.com/464871/90435953-b2e6da80-e084-11ea-8971-b6d364cca92a.png)

**Comment by KristinaRiemer** [comment]
@dlebauer where do you want to logo located? I put an image of the top of the current website in [a Google slide](https://docs.google.com/presentation/d/1J1_9nCukabECgv-wS9DM2t3-weDrgsXe2-M4Gb5Bsk0/edit#slide=id.p), if you want to just move that logo to where you'd like it.

**Comment by KristinaRiemer** [comment]
Wait, how does this look? There's an easy automated way to do this with Hugo. 
![Screen Shot 2020-09-18 at 12.06.41 PM.png](https://images.zenhubusercontent.com/5c38e1da82e03870988b36b1/1d4c740b-9995-4038-8436-91f9720a0710)

**Comment by dlebauer** [comment]
roughly like 
![image](https://user-images.githubusercontent.com/464871/93655199-f6f83280-f9d6-11ea-946c-543fa1e3e34f.png)

**Comment by Chris-Schnaufer** [comment]
@dlebauer @KristinaRiemer What is the status of this issue?

**Comment by dlebauer** [comment]
* [ ] need top red banner bar
* [ ] logo needs improvement - currently in https://github.com/az-digitalag/group-website/pull/21 it looks like this: 
![image](https://user-images.githubusercontent.com/464871/98424895-85d91100-2050-11eb-9a09-e360cb1bfcf7.png)
 
![image](https://user-images.githubusercontent.com/464871/98424914-9e492b80-2050-11eb-9e5b-6715484bd089.png)

**Comment by KristinaRiemer** [comment]
@dlebauer what exactly is wrong with that logo?

**Comment by dlebauer** [comment]
it appears to have a 'drop shadow' effect (grey line around it ... see image below) even though the logo in https://github.com/az-digitalag/organization/issues/273#issue-680472780 doesn't

![image](https://user-images.githubusercontent.com/464871/98594696-46016c00-2292-11eb-90ae-cf1a94985b99.png)

**Comment by KristinaRiemer** [comment]
@Chris-Schnaufer if you're able to attempt this, or also @julianpistorius & @MagicMilly?

**Comment by Chris-Schnaufer** [comment]
@KristinaRiemer I can take a look.

**Comment by Chris-Schnaufer** [comment]
The issue is that the image was captured (or exported, or ...) with the drop shadow. Attaching new image & also sending to Kristina.
 ![logo.png](https://images.zenhubusercontent.com/5c14118eee1e975f1842e1c2/83f40511-0116-48d4-9378-75b7dfa8f4dd)

**Comment by Chris-Schnaufer** [comment]
The actual HTML as exposed by inspecting the page looks like the following:
<img width="782" alt="Screen Shot 2020-11-13 at 12 52 44 PM" src="https://user-images.githubusercontent.com/45463434/99115247-56298c00-25af-11eb-854c-1d1919652197.png">
Each `::before` and `::after` has additional CSS associated with it. The URL for the CSS files are:
- https://digital.arizona.edu/ua-bootstrap/lib/ua-bootstrap.css
- https://cdn.uadigital.arizona.edu/lib/ua-brand-icons/v1.1.0/ua-brand-icons.min.css

I'm looking to see where/how this can be added

**Comment by dlebauer** [comment]
@Chris-Schnaufer have you done this or should this stay open until this is implemented?

**Comment by Chris-Schnaufer** [comment]
@dlebauer I have not done this. The approach I'm suggesting may be simplistic in that there may end up being conflicting CSS between what UA has and what the website uses. A more detailed approach may be needed where only the UA CSS used by the elements are brought over - this involves tracking down what's used and updating the website CSS. I did a preliminary look and this more detailed approach appears to avoid conflicts and should be workable.

**Comment by dlebauer** [comment]
@Chris-Schnaufer I have done what you said

* put 2 css files in assets
* move navbar.html to layouts/partials
* added in code chunk from OP above

but nothing happened. You can  see these changes w/ code chunk commented out in the 'header' branch https://github.com/az-digitalag/group-website/compare/header?expand=1

the code chunk is supposed to go between body tags, but there are none in navbar.html, and it doesn't help if I add them

**Comment by Chris-Schnaufer** [comment]
I have tried to add the suggested HTML for the red bar containing the white "University of Arizona" and have run into problems with the theme conflicting with the HTML.

A different approach will be needed to display this bar. The bar and text needs to break out from the Navigation control since the control uses the flex-box layout scheme. An undesirable approach would be to modify the theme code which would make upgrades much more difficult.

**Comment by Chris-Schnaufer** [comment]
Was able to get the banner displayed by adding a top margin to the `nav` wrapper and adding the background with text as an absolutely positioned element.

PR: https://github.com/az-digitalag/group-website/pull/23
