### ISSUE TITLE
Twitter Curator, Sprint 42

### ISSUE THREAD

**Issue by MagicMilly** [az-digitalag/organization#279]
**Tasks to do**
- [ ] First week tweet, retweet with comment, or reply
- [ ] Second week

**Ideas**
Announce new group website once it's ready

**Reason**
Increased Visibility on social media for our group

**Comment by KristinaRiemer** [comment]
A little late and not what was prescribed, but there is a tweet thread now! https://twitter.com/DigitalAgGroup/status/1306314798330769409
