### ISSUE TITLE
Update OSF re what Icebox, Backlog, Ready pipelines mean

### ISSUE THREAD

**Issue by Chris-Schnaufer** [az-digitalag/organization#28]
Details on what these lanes mean
Define roles Product Manager & Projext Managers roles are

https://osf.io/tzmhp/wiki/Project%20Management/?edit&view&menu

**Comment by dlebauer** [comment]
Looks like @Chris-Schnaufer made updates here: https://osf.io/tzmhp/wiki/Project%20Management/

I will put on my review list and review

**Comment by dlebauer** [comment]
I've updated a few things, some are meaningful. 

Here is the diff: https://osf.io/tzmhp/wiki/Project%20Management/?compare=45&menu

![image.png](https://images.zenhubusercontent.com/583f321cb9dc3c622022c169/4899faf1-6d7a-4c8d-960c-f022be09f17a)
