### ISSUE TITLE
A working pipeline on a small scale

### ISSUE THREAD

**Issue by julianpistorius** [az-digitalag/organization#29]
- [x] Start Clowder via Docker
- [x] Get BETY key from @max-zilla
- [x] Start an extractor
- [x] Upload a raw file & metadata
- [ ] Confirm that the extractor worked and the data was processed correctly

**Comment by julianpistorius** [comment]
Notes from Max:

The quickest way to set up a working pipeline on a small scale would be to start with Rob’s suggestion in the channel. There’s no Puppet script or anything to set up the various VMs we use at once.
 
1 – Starting Clowder via Docker

https://opensource.ncsa.illinois.edu/bitbucket/projects/CATS/repos/clowder/browse/docker-compose.yml

https://opensource.ncsa.illinois.edu/confluence/display/CATS/Running+Clowder+using+Docker

Download this YAML file and use docker-compose up command, it will start up a small docker cluster with Clowder + MongoDB + Elasticsearch + RabbitMQ for you. You should then be able to reach Clowder at http://localhost:9000. You should be able to reach RabbitMQ management console at http://localhost:15672/#/.
 
 
2 – Starting an extractor

As we discussed, we run a bunch of these managed using Kubernetes. But for a local test, you can start with one extractor, that converts the stereo RGB camera’s raw bin format into geotiff.

https://hub.docker.com/r/terraref/ext-stereorgb-bin2tif

Both extractor & the upload step 3 below will use our sensor_fixed_metadata repository so you can go ahead and pull that externally:

```bash
cd /Users/mburnette
git clone https://github.com/terraref/sensor-metadata.git
```

Try docker pull terraref/ext-stereorgb-bin2tif to pull this one down, we can then run it locally and connect it to the local RabbitMQ you started in step 1. We need to pass in a few environment variables when running the extractor so it knows where to listen for messages. When I’m testing this I use (141.142.22.37 is my IP, you might be able to drop that add-host bit):

```bash
docker pull terraref/ext-stereorgb-bin2tif:1.3
docker run -p 5672 -p 9000 --add-host="localhost:141.142.22.37" -e RABBITMQ_URI=amqp://guest:guest@localhost:5672/%2f -e RABBITMQ_EXCHANGE=clowder -v /Users/mburnette/sensor-metadata:/home/extractor/sites/ua-mac/sensor-metadata -e REGISTRATION_ENDPOINTS=http://localhost:9000/api/extractors?key=r1ek3rs -e BETYDB_KEY=SECRET_KEY terraref/ext-stereorgb-bin2tif:1.3
```

I can share the BETY key we use via Slack if you don’t have one already. This hits Clowder’s /api/extractors endpoint with the default API key to register the extractor, as well as sets the RabbitMQ URL to listen on (the RMQ AMQP port is 5672, the dashboard is 15672). If this works, you should see an entry for terra.stereo-rgb.bin2tif show up under Queues on RMQ dashboard.

3 – Uploading a raw file & metadata

Final step here is to download a left + right .bin file and a metadata.json file representing a single stereo RGB capture. You can find that on Terraref globus under /ua-mac/raw_data/stereoTop, but I’ve uploaded a sample dataset and script to create it here:

https://drive.google.com/drive/folders/1RjvcgrPQz7nH8LTGdN37Nexz6l6VTKpz?usp=sharing

(from https://terraref.ncsa.illinois.edu/clowder/datasets/5c93b00a4f0c2eee7b283ef3)

The script will need to be edited to include your username/password for Clowder account you create. Sign up for a Clowder account and check the docker logs to see the content of the confirmation email since you won’t have an emails server set up.
 
The metadata.json is the uncleaned format from the gantry, we use our terrautils python script to clean it and upload it. Terrautils requires GDAL and some other tricky bindings so it’s quickest to simply mount the folder containing those 3 files into a terrautils docker container and upload it that way, e.g.:

Start the container, use -v to mount the directory containing bins+json to /data

```bash
docker run --add-host="localhost:141.142.22.37" -p 9000 -v "/Users/mburnette/globus/stereoTop - 2018-05-07__16-58-55-097/":/data -e BETYDB_KEY=SECRET_KEY -v /Users/mburnette/sensor-metadata:/home/extractor/sites/ua-mac/sensor-metadata -it terraref/terrautils:1.5 /bin/bash
```
 
(insider container) Run script to clean & upload data

```bash
cd /data
python pipeline_setup_example.py
```
 
If the extractor is properly registered, running this script will cause a message to be sent to bin2tif extractor to begin processing. You can then check logs of the extractor container to see if it’s working. It will try to create a new dataset with the output files.
 
…
 
Ok so there’s the first brain dump. Obviously this is a tiny simulacrum of the full pipeline, which would require ~20 more extractors and a day’s worth of stereo RGB and other sensor data to create field mosaics, etc. But let’s start here and build on it.

**Comment by julianpistorius** [comment]
Step 1 done. Launched it on a virtual machine.

![Screen Shot 2019-07-01 at 18 21 12](https://user-images.githubusercontent.com/742633/60475646-ecce0500-9c67-11e9-84de-74b2efd221ae.png)

(Re `localhost:9000` - I'm using port-forwarding over SSH.)

**Comment by julianpistorius** [comment]
Life-hack: Use `sshuttle` to securely expose private Docker networks on a remote machine to your local machine.

Let's say I want to access some Docker services running on IP addresses like `172.18.0.1`, and I don't want to expose these ports to the world, and I don't want to do individual SSH port-forwarding.

On your local machine/laptop:

```bash
pip install sshuttle  # Or brew install sshuttle
sshuttle -r <some.remote.host.where.docker.is.running> 172.0.0.0/8
```

Then on your local machine/laptop open a browser and you should be able to access URLs like this: `http://172.19.0.4:15672` (RabbitMQ panel)

**Comment by Chris-Schnaufer** [comment]
@julianpistorius Have you run RGB data through this?

**Comment by julianpistorius** [comment]
> @julianpistorius Have you run RGB data through this? Can you also add your comments to the TERRA REF admin repo?

Hi @Chris-Schnaufer. No, I have not. Doing that next.

**Comment by julianpistorius** [comment]
Done.

**Comment by julianpistorius** [comment]
@max-zilla & @Chris-Schnaufer do these look right?

![Screen Shot 2019-08-01 at 16 10 48](https://user-images.githubusercontent.com/742633/62333153-31bba600-b477-11e9-9290-d64c204e734c.png)
![Screen Shot 2019-08-01 at 16 10 58](https://user-images.githubusercontent.com/742633/62333154-31bba600-b477-11e9-8d68-1ee32ea9ab04.png)
![Screen Shot 2019-08-01 at 16 11 05](https://user-images.githubusercontent.com/742633/62333155-31bba600-b477-11e9-9cbb-21d5439cdc52.png)
![Screen Shot 2019-08-01 at 16 11 18](https://user-images.githubusercontent.com/742633/62333156-31bba600-b477-11e9-87bc-29b6f75afb92.png)

**Comment by julianpistorius** [comment]
Update: Looks like the problem was that I did not know that I have to manually submit the dataset for extraction. I did that and now I get a 401 error, so there's probably something wrong with one of the keys/tokens. Should have that figured out today. 🤞

**Comment by julianpistorius** [comment]
Calling it good-enough-for-now and moving on to standing up full pipeline.
