### ISSUE TITLE
Create a metadata template that will be used to specify an experiment 

### ISSUE THREAD

**Issue by dlebauer** [az-digitalag/organization#3]
Should include a google spreadsheet + request for shapefiles

**Comment by kimberlyh66** [comment]
@dlebauer When you say `experiment` do you mean `sub experiment` or the experiment as a whole, including `all sub experiments`. This [sample template](https://docs.google.com/spreadsheets/d/1Fr_8xYOucyCQ9WH5_1bfPTMpm3IhKX5oqW4UOMvPoSY/edit#gid=0) that I created is for individual sub experiments. I would have to add another field to the sites and treatments sheets if the template is for the entire experiment.

**Comment by dlebauer** [comment]
It would be good to provide the option of supporting both experiments and sub-experiments.

**Comment by kimberlyh66** [comment]
[Sample template](https://docs.google.com/spreadsheets/d/1Fr_8xYOucyCQ9WH5_1bfPTMpm3IhKX5oqW4UOMvPoSY/edit#gid=0) has been updated to support sub-experiments
