### ISSUE TITLE
Review and run vignette for running ED2

### ISSUE THREAD

**Issue by KristinaRiemer** [az-digitalag/organization#30]
The vignette is here: https://github.com/az-digitalag/model-vignettes/blob/master/ED2/ed2_in_pecan.Rmd

It assumes running Rstudio in Welsch but could also be done using Rstudio on VICE or in a local development environment. The only real dependency on welsch is that it connect to the welsch version of BETYdb

**Comment by dlebauer** [comment]
I am closing this - more useful to get this running in singularity on UA HPC
