### ISSUE TITLE
Finalize planning for next ODDPIG meeting

### ISSUE THREAD

**Issue by KristinaRiemer** [az-digitalag/organization#317]
Planning
  * [x] Draft a letter
     * Create a form preferred day, time, frequency (month)
  * [x] Come up with a monthly time and schedule all meetings in advance
  * [x] ~Import members to myemma~ using mailchimp pending myemma configuration
  * [x] Send the email

First meeting
  * [x] Create an agenda
  * [x] Draft a letter
  * [x] Create a zoom registration
  * [x] Send out a meeting notice

Next step: hold the meeting
  * [ ] send reminders

**Comment by dlebauer** [comment]
Boom scheduled! https://mailchi.mp/41365d398da7/oddpig_third_thursdays
