### ISSUE TITLE
First Steps: Chatbot

### ISSUE THREAD

**Issue by MagicMilly** [az-digitalag/organization#324]
- Research what's available, decide which to use
- Add to website (?)
- Break this ticket into smaller tasks?

Placeholder ticket for @julianpistorius to review and edit as needed

**Developing Skills**

- [x] Emily to read Chapter 8 "Before the Project" of _The Pragmatic Programmer_
- [x] Take notes of process

**Comment by dlebauer** [comment]
Before deciding how we want to provide the world with access, we should be clear about what we want to offer, and whether we actually want to allow people to contact us through a chatbot (and commit to monitoring it full time). Would email be sufficient or at least a good place to start?

- If we go the chatbot route, Matt Rahr suggested trellis support or zendesk; these are paid solutions that we might have access to / could buy into (though I am not sure if these are more fully featured than what we need).

**Comment by MagicMilly** [comment]
Removing the milestone on this until there's more time for others to collaborate and brainstorm

**Comment by julianpistorius** [comment]
I'd like to start experimenting with this - starting with just the people in our group, and collaborators like Tyson and Sue Malusa.

Should I get in touch with Matt to see what's involved with using ZenDesk?

**Comment by dlebauer** [comment]
I think the first step would be to make a list of user types and paths to engagement before implementing setting up a chat bot. My hunch is that office hours, presentations to faculty, and other forms of outreach would be more effective.

**Comment by dlebauer** [comment]
has been superseded by office hours
