### ISSUE TITLE
Curate a sample of NPN data

### ISSUE THREAD

**Issue by dlebauer** [az-digitalag/organization#338]
Start with Red Maple (most observations) and lilac (common genotype across sites)
This is the plant leaderboard https://www.usanpn.org/nn/leaderboard-plants

- use the npn_download_magnitude_phenometrics function. This will return data for species/phenophases in intervals across the specified time period frequency and provide the proportion of plants in phase for each interval. Start w/ period_frequency at 4, and if the data are very sparse increase to 7. 
- we are interested in finding the date on which it reaches a stage where 1/2 of the flowers are open
- need to use rnpn version from github rather than cran

TODO:
* [ ] download data for red maple % open flowers to review; filter for 25-49% and 50-74%
* [ ] plot day of year vs/ '% open flowers' for all red maple
* [ ] repeat for lilac
* [ ] summarize findings and follow up w/ discussion

**Comment by KristinaRiemer** [comment]
@dlebauer who is this issue for? No one is assigned.
