### ISSUE TITLE
Make a list of user types and paths to engagement for Data Science Helpdesk

### ISSUE THREAD

**Issue by MagicMilly** [az-digitalag/organization#339]

**Comment by julianpistorius** [comment]
Progress and notes: https://hackmd.io/@eywX1MatRnyBtYFBB3Gqwg/S1IG7W7KD

**Comment by julianpistorius** [comment]
Moving this to backlog for now.

**Comment by dlebauer** [comment]
I've added most of the content from the Hackmd to 
 our 'outreach' wiki... https://osf.io/h9vqt/wiki/home/ and https://osf.io/h9vqt/wiki/Weekly%20Office%20Hours/

a lot of the content on that hackmd was more general than the 'help desk'

We haven't created a robust 'personas and pathways' but I think we have a good idea of who will be using which services - sufficient to close this issue
