### ISSUE TITLE
Create a blog post about Exosphere paper and SC presentation

### ISSUE THREAD

**Issue by dlebauer** [az-digitalag/organization#345]
* Presentation: https://sc20.supercomputing.org/presentation/?id=ws_scc108&sess=sess203
* Paper https://arxiv.org/abs/2008.10640
* Repository: https://gitlab.com/exosphere

**Comment by julianpistorius** [comment]
Draft: <https://hackmd.io/@julianp-diag/HyeRJVndu>

**Comment by dlebauer** [comment]
please keep open until posted or create a follow on issue

**Comment by julianpistorius** [comment]
@dlebauer & @Chris-Schnaufer I'd appreciate another review and sign-off before posting.

**Comment by julianpistorius** [comment]
Done: https://datascience.cals.arizona.edu/news/2021/06/exosphere-researcher-friendly-interface-cloud-computing
