### ISSUE TITLE
Change DE canopy cover tool so it doesn’t require multiple file selector 

### ISSUE THREAD

**Issue by dlebauer** [az-digitalag/organization#346]
From Matt King 

> Unfortunately, your app is using a Cyverse field type called MultiFileSelector which happens to be one of the few input types we haven't built out support for.

> If you guys created a version that only had a single FileInput for a GeoJSON file (or multiple single FileInputs for all the required files for a shape file), that would work for us

**Comment by Chris-Schnaufer** [comment]
Waiting for app to become public
