### ISSUE TITLE
Make a python script to process RAW to GeoTiff using TERRA REF sample data

### ISSUE THREAD

**Issue by Chris-Schnaufer** [az-digitalag/organization#35]
Putting this ticket here due to https://github.com/sateeshperi/cyverse_terraref_pilot not on our board.

The book keeping for the current RAW to GeoTiff extractor prevents it from working in the CyVerse environment. This ticket is to provide a minimal script to take the RAW file along with select gantry metadata  and produce a GeoTiff

**Comment by dlebauer** [comment]
Script written, handed off to Sateesh
