### ISSUE TITLE
Match all section styles on website

### ISSUE THREAD

**Issue by KristinaRiemer** [az-digitalag/organization#352]
Currently the Projects and Services sections on the website have different colors and fonts than the other sections, because they are the slider widget type. 

The Projects and Services sections currently have a dark grey background, with light grey header text and white content text. All the non-header text is also larger relative to other sections. See screenshot of this: 
![Screen Shot 2020-12-11 at 11 11 58 AM](https://user-images.githubusercontent.com/6686508/101940860-62037080-3ba4-11eb-809e-8b7ccf23b1d9.png)

The other sections have backgrounds that are either white or a very light grey, and they alternate. All of the text is black also. See screenshot: 
![Screen Shot 2020-12-11 at 11 21 11 AM](https://user-images.githubusercontent.com/6686508/101940886-6e87c900-3ba4-11eb-9b82-f9cfdb6b7c11.png)

Based on this, the Projects section needs a white background while Services needs light grey background. The subheaders text for both should be 25.2 and the paragraph text 16.8 in size. And all the text needs to be black.

**Comment by dlebauer** [comment]
no longer necessary as we move (back) to Drupal quickstart
