### ISSUE TITLE
Change website domain name

### ISSUE THREAD

**Issue by KristinaRiemer** [az-digitalag/organization#353]
Instructions for how to do this on Netlify: https://docs.netlify.com/domains-https/custom-domains/#assign-a-domain-to-a-site. We want to change it to https://datascience.cals.arizona.edu/, but probably requires getting some sort of permission from the university.

**Comment by dlebauer** [comment]
Have asked Toby to add CNAME record

```
datascience.cals CNAME quizzical-perlman-731692.netlify.app.
```

![image.png](https://images.zenhubusercontent.com/583f321cb9dc3c622022c169/9562f9ec-4b94-4eac-ac0e-6ed0a6646073)

**Comment by dlebauer** [comment]
moving back to Drupal per convo w/ CCT
