### ISSUE TITLE
Continue developing pipeline presentation

### ISSUE THREAD

**Issue by Chris-Schnaufer** [az-digitalag/organization#38]
From feedback in for #21:

Looks like a great start. Definitely has most of the critical content in place; it will probably be worthwhile to go through this with friendly users in the group to see if it provides them with what they need to take it from here.

Also, I started very roughly sketching a few additional slides that I think would be helpful:

a motivating overview: what is the problem you are solving? who is the audience?
highest level view of what will happen highest level overview
a slide w/ references / links to relevant resources including osf, github, links to jupyter notebook
Finally, in the instruction slides, provide actual commands (at a minimum, screenshots w/ links to the jupyter notebook).

**Comment by dlebauer** [comment]
This is an old issue, but it would be useful to make the slides available in the OSF site (e.g. make sure it is in the google docs directory associated w/ the dpp osf site). Otherwise this can be closed.
