### ISSUE TITLE
add season 9 plot info for N and S

### ISSUE THREAD

**Issue by dlebauer** [az-digitalag/organization#39]
Placeholder for https://github.com/terraref/reference-data/issues/269

**Comment by Chris-Schnaufer** [comment]
@kimberlyh66 Please assign to sprint and estimate this ticket

**Comment by kimberlyh66** [comment]
@dlebauer I am not sure what distance the north range sites (55-94) need to be moved. Can you help me with this?

**Comment by dlebauer** [comment]
You are correct this is confusing - I've updated the issue to ask for more guidance https://github.com/terraref/reference-data/issues/269#issuecomment-520157956

**Comment by dlebauer** [comment]
https://docs.terraref.org/user-manual/how-to-access-data/using-betydb-trait-data-experimental-metadata/accessing-betydb-via-arcmap-and-other-gis-software
-- 

_______________________

*David LeBauer*
Director of Data Sciences
Arizona Experiment Station
THE UNIVERSITY OF ARIZONA

Bioscience Research Labs, 207
1230 N Cherry Ave | Tucson, AZ 85721
Office: 520-621-4381
dlebauer@email.arizona.edu
orcid <https://orcid.org/0000-0001-7228-053X> | twitter
<https://twitter.com/dlebauer> | github <https://github.com/dlebauer> |
linkedin <https://www.linkedin.com/in/dlebauer/>

**Comment by kimberlyh66** [comment]
Is the north field shorter in length than the south field? 

You mentioned that ranges should go from 55-94 in the north field. However, the south field has ranges 1-54 and adding 54 to each of these range numbers results in the north field having ranges 55-108.

**Comment by dlebauer** [comment]
@kimberlyh66 apparently there are only 98 ranges ... https://docs.google.com/document/d/1YDivOXxt0n052WJyHkiz7eolOzNOvVEvS0v4TQ0Hldg/edit

**Comment by kimberlyh66** [comment]
@dlebauer Here are updated sql statements. The statements should be run in the following order:

Add season 9 north field plots:
[season9_northfield_updated.txt](https://github.com/az-digitalag/organization/files/3557705/season9_northfield_updated.txt)

Move north field plots ~231.2 meters north:
```sql
update sites
set geometry = st_translate(geometry, 0, +0.00210)
where sitename like 'MAC Field Scanner Season 9%';
```
Add season 9 south field plots:

```sql
with season9 as (
  select city, state, replace(sitename, 'Season 7', 'Season 9') as sitename, greenhouse, geometry, time_zone from sites where sitename like '%Season 7%' 
)
insert into sites (city, state, sitename, greenhouse, geometry, time_zone) select * from season9;
```

Here is an image of the season 9 north field plots over a full field image:
<img width="446" alt="season9_northfield" src="https://user-images.githubusercontent.com/44081116/63984138-9d952c80-ca7e-11e9-99ca-6752c872a1f9.png">

**Comment by dlebauer** [comment]
I've added these sites - do we also need to add experiments_sites and sites_cultivars records? Can you please create a new issue for that?

**Comment by kimberlyh66** [comment]
Yes, experiments_sites and sites_cultivars records need to be added. I will create the new issue.
