### ISSUE TITLE
Document NAPPN TERRA REF workshop feedback

### ISSUE THREAD

**Issue by KristinaRiemer** [az-digitalag/organization#393]
- [ ] ~Send out [feedback form](https://docs.google.com/forms/d/1s7-ypc-YQxEk7ar3WA9hoTjHKkzh_F12rLKGu4fEBbE/edit?ts=602bf756&gxids=7628) to participants~
- [x] Get Whova feedback form 
- [x] Collate feedback

**Comment by KristinaRiemer** [comment]
@dlebauer do we still want to do this? I think it's a good idea, but it might be too late to send anything to participants ourselves. And I haven't heard anything about NAPPN's feedback from participants?

**Comment by dlebauer** [comment]
I'll ask Noah if we can get the feedback.

**Comment by dlebauer** [comment]
need to be better next time about quick follow up.

**Comment by KristinaRiemer** [comment]
At least it's all positive feedback! 😂
