### ISSUE TITLE
Office hours: Announce office hours on CALS email list

### ISSUE THREAD

**Issue by julianpistorius** [az-digitalag/organization#396]

**Comment by julianpistorius** [comment]
@dlebauer could you please review draft and email Matt?

**Comment by dlebauer** [comment]
sent

**Comment by dlebauer** [comment]
submissions are done through Compass website

- Weekly Bulletin https://compass.arizona.edu/bulletin
- Tuesday Morning Notes: tmn@cals.arizona.edu

**Comment by julianpistorius** [comment]
Thanks @dlebauer!
