### ISSUE TITLE
Mock up web site

### ISSUE THREAD

**Issue by dlebauer** [az-digitalag/organization#4]

**Comment by dlebauer** [comment]
- [ ] Discuss during content meeting
- [ ] Mock up UI (create tickets & whatever else needs to be done)

**Comment by Chris-Schnaufer** [comment]
Closing with site map developed

**Comment by dlebauer** [comment]
we have a sitemap, hannah will design the interface
[Data Science Site Map v2.pdf](https://github.com/az-digitalag/organization/files/3189010/Data.Science.Site.Map.v2.pdf)
. 

![Uploading image.png…]()
