### ISSUE TITLE
BrAPI hackathon week 1 goals

### ISSUE THREAD

**Issue by KristinaRiemer** [az-digitalag/organization#403]
* [x] Learn about v2 migration

Moved to week 2 due to scheduling issues: 
* [ ] review architecture and docs w/ Rob
* [ ] review and prioritize open issues https://github.com/terraref/brapi/issues
* [ ] create new issues for v2 migration

**Comment by dlebauer** [comment]
* [ ] Learn about v2 migration
* [ ] review and prioritize open issues https://github.com/terraref/brapi/issues
* [ ] create new issues for v2 migration
