### ISSUE TITLE
(KR) Create virtual machines for UA Pipeline

### ISSUE THREAD

**Issue by julianpistorius** [az-digitalag/organization#41]
Automated & configurable so can be re-used by other organizations.

- [x] New repo (https://github.com/terraref/terraref-terraform)
- [x] Map OpenStack provider flavors to server requirements
- [x] README.md
- [x] Sort out OpenStack creds
    - <https://www.inovex.de/blog/managing-secrets-openstack-terraform/>
- [x] PostgreSQL VM (medium1)
    - [x] `01_network.tf`
    - [x] `01_storage.tf`
    - [x] `02_security.tf`
    - [x] `03_user.tf`
    - [x] `04_compute_postgresql.tf`
- [x] Mongo VM
    - [x] `04_compute_mongo.tf`
- [x] Barman https://github.com/terraref/terraref-terraform/issues/4
- [x] Ops Manager https://github.com/terraref/terraref-terraform/issues/5

**Comment by julianpistorius** [comment]
Implemented by: https://github.com/terraref/terraref-terraform/pull/1

**Comment by KristinaRiemer** [comment]
Undergoing second round of review by Rob.

**Comment by julianpistorius** [comment]
Follow-up issues:

https://github.com/terraref/terraref-terraform/issues/4
https://github.com/terraref/terraref-terraform/issues/5
