### ISSUE TITLE
Investigate cause of Travis CI error with SPARC'd

### ISSUE THREAD

**Issue by Chris-Schnaufer** [az-digitalag/organization#428]
Travis CI is reporting a credential issue for SPARC'd.

Determine the cause and propose fix

**Comment by Chris-Schnaufer** [comment]
The problem appears to be an expired OAUTH token.

**Comment by julianpistorius** [comment]
I just ripped out Travis CI and replaced it with GitHub actions.

https://github.com/CulverLab/sparcd/actions

https://github.com/CulverLab/sparcd/releases
