### ISSUE TITLE
Fix BrAPI treatment error

### ISSUE THREAD

**Issue by KristinaRiemer** [az-digitalag/organization#438]
Multiple treatmentDbId per observationunitDbId, when there should only be one. See example below from https://brapi.workbench.terraref.org/brapi/v1/observationunits?studyDbId=6000000010: 

```
{
                "germplasmDbId": "6000000890",
                "germplasmName": "PI563002",
                "observationUnitName": "MAC Field Scanner Season 4 Range 51 Column 11 E",
                "observations": [
                    {
                        "observationDbId": "6001947784",
                        "observationTimeStamp": "2017-05-22T05:00:00Z",
                        "observationVariableDbId": "6000000260",
                        "observationVariableName": "stand_count",
                        "operator": "Newcomb, Maria",
                        "quality": "unchecked",
                        "replicate": null,
                        "value": "31"
                    }
                ],
                "observationunitDbId": "6000008564",
                "seasonDbId": "a8317fa6b59bfa8cfe29004423f5613b",
                "studyDbId": "6000000010",
                "treatmentDbId": "6000000024",
                "treatments": [
                    {
                        "factor": "MAC Season 4: BAP water-deficit stress Aug 1-14",
                        "modality": "Between Aug 1-14, experimental plots in Cols 5, 6, 7, 8, 12, 13, 14, 15 and border plots in Col 16 were established as water-deficit blocks with no irrigation (by capping drip lines)."
                    }
                ]
            },
            {
                "germplasmDbId": "6000000890",
                "germplasmName": "PI563002",
                "observationUnitName": "MAC Field Scanner Season 4 Range 51 Column 11 E",
                "observations": [
                    {
                        "observationDbId": "6001947784",
                        "observationTimeStamp": "2017-05-22T05:00:00Z",
                        "observationVariableDbId": "6000000260",
                        "observationVariableName": "stand_count",
                        "operator": "Newcomb, Maria",
                        "quality": "unchecked",
                        "replicate": null,
                        "value": "31"
                    }
                ],
                "observationunitDbId": "6000008564",
                "seasonDbId": "a8317fa6b59bfa8cfe29004423f5613b",
                "studyDbId": "6000000010",
                "treatmentDbId": "6000000026",
                "treatments": [
                    {
                        "factor": "MAC Season 4: BAP water-deficit stress Aug 15-30",
                        "modality": "Between Aug 15-30, experimental plots in Cols 2, 3, 4, 9, 10, 11 and border plots in Col 1 were established as water-deficit blocks with no irrigation (by capping drip lines)."
                    }
                ]
            }
```

Either an error in the underlying database data, or in the API itself.

**Comment by dlebauer** [comment]
in the end, the problem is that we are returning duplicate records from this query in observationunits.py:

```py
select
  v.id :: text as observationVariableDbId,
  v.name as observationVariableName,
  t.id :: text as observationDbId,
  t.mean :: text as value,
  t.date as observationTimeStamp,
  s.sitename as observationUnitName,
  s.id :: text as observationUnitDbId,
  cv.id :: text as germplasmDbId,
  cv.name as germplasmName,
  es.experiment_id :: text as studyDbId,
  et.treatment_id :: text as treatmentDbId,
  seasons.id :: text as seasonDbId,
  tr.name as factor,
  tr.definition as modality,
  t.entity_id :: text as replicate,
  c.author as operator,
  t.checked as quality
from
  traits t
  left join variables v on t.variable_id = v.id
  left join sites s on t.site_id = s.id
  left join experiments_sites es on t.site_id = es.site_id
  left join experiments e on es.experiment_id = e.id
  left join experiments_treatments et on e.id = et.experiment_id
  left join treatments tr on t.treatment_id = tr.id
  left join citations c on t.citation_id = c.id
  left join cultivars cv on t.cultivar_id = cv.id,
  (select distinct extract (year from start_date) as year,
      LTRIM(RTRIM(SPLIT_PART(name, ': ', 1))) as season,
      md5(LTRIM(RTRIM(SPLIT_PART(name, ': ', 1)))):: varchar(255) as id
    from experiments) seasons
where
  t.checked > -1
  and t.access_level = 4
  and seasons.season = LTRIM(RTRIM(SPLIT_PART(e.name, ': ', 1))) 
```

**Comment by dlebauer** [comment]
got it! needed to join the experiments_sites and experiments_treatments to traits before joining experiments

**Comment by KristinaRiemer** [comment]
I don't think this is quite exactly what we were trying to do? It looks like now the same observationunitDbId is repeated many times with the same treatment. From https://brapi.workbench.terraref.org/brapi/v1/observationunits?studyDbId=6000000010

      {
        "germplasmDbId": "6000000826",
        "germplasmName": "PI330803",
        "observationUnitName": "MAC Field Scanner Season 4 Range 42 Column 15",
        "observations": [
          {
            "observationDbId": "6004792786",
            "observationTimeStamp": "2017-08-08T19:00:00Z",
            "observationVariableDbId": "6000000007",
            "observationVariableName": "canopy_height",
            "operator": "Zongyang, Li",
            "quality": "unchecked",
            "replicate": null,
            "value": "305"
          }
        ],
        "observationunitDbId": "6000005902",
        "seasonDbId": "a8317fa6b59bfa8cfe29004423f5613b",
        "studyDbId": "6000000010",
        "treatmentDbId": "6000000024",
        "treatments": [
          {
            "factor": "MAC Season 4: BAP water-deficit stress Aug 1-14",
            "modality": "Between Aug 1-14, experimental plots in Cols 5, 6, 7, 8, 12, 13, 14, 15 and border plots in Col 16 were established as water-deficit blocks with no irrigation (by capping drip lines)."
          }
        ]
      },
      {
        "germplasmDbId": "6000000826",
        "germplasmName": "PI330803",
        "observationUnitName": "MAC Field Scanner Season 4 Range 42 Column 15",
        "observations": [
          {
            "observationDbId": "6004793628",
            "observationTimeStamp": "2017-08-10T19:00:00Z",
            "observationVariableDbId": "6000000007",
            "observationVariableName": "canopy_height",
            "operator": "Zongyang, Li",
            "quality": "unchecked",
            "replicate": null,
            "value": "308"
          }
        ],
        "observationunitDbId": "6000005902",
        "seasonDbId": "a8317fa6b59bfa8cfe29004423f5613b",
        "studyDbId": "6000000010",
        "treatmentDbId": "6000000024",
        "treatments": [
          {
            "factor": "MAC Season 4: BAP water-deficit stress Aug 1-14",
            "modality": "Between Aug 1-14, experimental plots in Cols 5, 6, 7, 8, 12, 13, 14, 15 and border plots in Col 16 were established as water-deficit blocks with no irrigation (by capping drip lines)."
          }
        ]
      },
      {
        "germplasmDbId": "6000000826",
        "germplasmName": "PI330803",
        "observationUnitName": "MAC Field Scanner Season 4 Range 42 Column 15",
        "observations": [
          {
            "observationDbId": "6004794336",
            "observationTimeStamp": "2017-08-15T19:00:00Z",
            "observationVariableDbId": "6000000007",
            "observationVariableName": "canopy_height",
            "operator": "Zongyang, Li",
            "quality": "unchecked",
            "replicate": null,
            "value": "307"
          }
        ],
        "observationunitDbId": "6000005902",
        "seasonDbId": "a8317fa6b59bfa8cfe29004423f5613b",
        "studyDbId": "6000000010",
        "treatmentDbId": "6000000024",
        "treatments": [
          {
            "factor": "MAC Season 4: BAP water-deficit stress Aug 1-14",
            "modality": "Between Aug 1-14, experimental plots in Cols 5, 6, 7, 8, 12, 13, 14, 15 and border plots in Col 16 were established as water-deficit blocks with no irrigation (by capping drip lines)."
          }
        ]
      },

**Comment by dlebauer** [comment]
I think it is what we want - each observationunitDbId refers to a specific plot. each plot has one treatment (treatmentDbId) but can have many observations (observationDbId)
