### ISSUE TITLE
Open Data Kit - evaluate efforts for: PECAN & BRAPI

### ISSUE THREAD

**Issue by Chris-Schnaufer** [az-digitalag/organization#443]
https://getodk.org/ - what it'd take to get data from OpenDataKit into BETYdb & develop BRAPI frontend, and write it up

**Comment by dlebauer** [comment]
Key question: how hard would it be to harmonize data from multiple independent ODK users? To ingest into BETYdb? To export as BrAPI?

- David to set up call w/ Yaw
- where are the API definitions? Database schema? 
- this is the docker compose info for ODK server: https://github.com/getodk/aggregate/blob/master/docs/build-and-run-with-docker-compose.md
- CGIAR webinar https://bigdata.cgiar.org/blog-post/webinar-innovations-in-odk-improving-data-collection-for-agriculture-and-scaling-to-the-global-community/
