### ISSUE TITLE
Develop workshop for fitting gas exchange data

### ISSUE THREAD

**Issue by jessicaguo** [az-digitalag/organization#453]
- [x] Schedule date, figure out how to add to website/advertise
- [x] Develop slides for using 'plantecophys' and the PeCAn photosynthesis package

**Comment by KristinaRiemer** [comment]
There's the beginnings of a workshop checklist at the bottom of the [workshops OSF page](https://osf.io/h9vqt/wiki/Workshops/) that you should feel free to use and improve!

**Comment by jessicaguo** [comment]
New [HackMD ](https://hackmd.io/-hSaZbuzQI-gAPP3pASvRw?both)created for workshop prep/content. Emailed out to CALS grad student listserv (Dr. Limesand unwilling to blast to whole college, EEB list, and more targeted emails to Jia Hu, Greg Barron Gafford, Elise Gornish). 

When developing presentation for workshop, share this [paper](https://www.sciencedirect.com/science/article/pii/S1574954121000236).

**Comment by dlebauer** [comment]
is it possible to set up a VICE app and / or Binder for others to use w/ packages and data pre-installed?

**Comment by jessicaguo** [comment]
Presentation created [here](https://docs.google.com/presentation/d/1bRNAq2z-rFHGy9rxGCtrS779XMqqeGhLNWu48YY2_jc/edit#slide=id.gd4359efa63_0_125).  Still need to add C4 Collatz model fitting somewhere

**Comment by KristinaRiemer** [comment]
@jessicaguo workshop notes and the presentation and such can go in the [CALS-workshops](https://github.com/az-digitalag/CALS-workshops) repo in a new folder.

**Comment by jessicaguo** [comment]
Follow up #467
