### ISSUE TITLE
(KR) Processing season's data in reasonable time with results comparable to NCSA pipeline

### ISSUE THREAD

**Issue by julianpistorius** [az-digitalag/organization#46]
As compared against NCSA.

Steps:

- [x] Move data from gantry cache server to UA using Globus #56
- [x] ~~Ensure pipeline triggers when data shows up on the Globus endpoint~~
    - not going to automatically process, will run in batches/cron
- [ ] Compare results with NCSA

**Comment by dlebauer** [comment]
Look at compression before tarring / try out different algorithms (see gdal)

**Comment by julianpistorius** [comment]
No longer relevant.
