### ISSUE TITLE
Create Binder for April gas exchange workshop

### ISSUE THREAD

**Issue by KristinaRiemer** [az-digitalag/organization#460]

**Comment by KristinaRiemer** [comment]
The repo with the Binder instance is a new one called [binder-gas-exchange-workshop](https://github.com/az-digitalag/binder-gas-exchange-workshop), and it can be launched by clicking the badge in the README. This worked for me, but @jessicaguo should test it out too by typing in `library(plantecophys)` once the RStudio appears.

**Comment by jessicaguo** [comment]
![image](https://user-images.githubusercontent.com/12022076/115939068-b4f20c00-a451-11eb-8698-48be849bf4d3.png)
I'm getting this error...

**Comment by KristinaRiemer** [comment]
This worked until I tried to include the Pecan photosynthesis package, which broke it due to dependencies. Will work on in the next sprint, see #461.
