### ISSUE TITLE
Complete organic farm analysis

### ISSUE THREAD

**Issue by jessicaguo** [az-digitalag/organization#463]
Per follow up meeting with Isaac, David, and Russell, rerun and present final analysis with consistent data sources.

**Comment by jessicaguo** [comment]
Met re: data with David and Isaac. Will rerun the analysis with updated data for gapfilling purposes. Will try to have individual slopes for each state (might be overparameterized).

**Comment by jessicaguo** [comment]
PR [2](https://github.com/az-digitalag/state_organic_ag/pull/2)

**Comment by jessicaguo** [comment]
Updated to include parameter table, new B figures indicating significant parameters, and model description in README.

**Comment by dlebauer** [comment]
updated sparkline tables and README and pushed to the main branch
