### ISSUE TITLE
Update CCT service catalog

### ISSUE THREAD

**Issue by dlebauer** [az-digitalag/organization#471]
https://docs.google.com/document/d/1LIxkktiP219_Xd24vXpgA1Qz7j7WcuRORtN26p2Qujw/edit?ts=6089f271&pli=1#

**Comment by dlebauer** [comment]
I've put in a solid first draft https://docs.google.com/document/d/1LIxkktiP219_Xd24vXpgA1Qz7j7WcuRORtN26p2Qujw/edit?ts=6089f271&pli=1#heading=h.u3t9l13i78l0 does anyone want to review?

**Comment by KristinaRiemer** [comment]
I can review this today!

**Comment by KristinaRiemer** [comment]
I did provide some edits and suggestions on this.

**Comment by dlebauer** [comment]
thanks! this is now posted on our website https://datascience.cals.arizona.edu/cals-data-science-incubator-program
