### ISSUE TITLE
create workshop notification mailing list

### ISSUE THREAD

**Issue by dlebauer** [az-digitalag/organization#472]
one more place to advertise to people who are actively engaged

**Comment by Chris-Schnaufer** [comment]
@dlebauer What's the status of this?

**Comment by dlebauer** [comment]
@Chris-Schnaufer I've assigned to @julianpistorius

**Comment by julianpistorius** [comment]
Matt Rahr pointed @dlebauer at 'myemma'.

Other options:

- University listserv
- Tinyletter
- ???
