### ISSUE TITLE
Create list / tag to identify interesting and fun stretch goals

### ISSUE THREAD

**Issue by dlebauer** [az-digitalag/organization#48]
- Blog posts with interesting data science content and visualizations
- Tweets
- HPC & distributed computing
- **Pro-active quality assurance & quality control (QA & QC)**
  - statistics
  - Rules-of-thumb for real-time monitoring output of image processing pipeline components to ensure biologically sensible results
  - [Hypothesis](https://hypothesis.readthedocs.io/en/latest/) - a library for doing [property based testing](https://hypothesis.works/articles/what-is-property-based-testing/) for quality control of extractors
  - [Continuous Analysis](https://greenelab.github.io/continuous_analysis/) for drone pipeline
- Insight & alerting dashboard
  - [Redash](https://redash.io)
  - Combine with QA & QC above
- Low-friction (and secure) ways to allow exploration of data
  - CyVerse's [VICE](https://learning.cyverse.org/projects/vice/en/latest/)
  - [PostgREST](http://postgrest.org/) in front of Geostreams & BETYdb
    - There is also an [R interface](https://github.com/clesiemo3/postgrestR/blob/master/DESCRIPTION) to PostgREST
  - [Datasette](https://github.com/simonw/datasette)
  - [Binder](https://mybinder.readthedocs.io/en/latest/)
  - [Code Ocean](https://codeocean.com)
  - Mozilla Iodide - [1](https://hacks.mozilla.org/2019/03/iodide-an-experimental-tool-for-scientific-communicatiodide-for-scientific-communication-exploration-on-the-web/), [2](https://github.com/iodide-project/iodide)
    - Plus [Beaker Browser](https://github.com/beakerbrowser/beaker)
- Alternative ways to enable sharing of large datasets
  - Maybe by enabling people to have their own local copy of databases - e.g. SQLite
  - [Logical replication](https://www.postgresql.org/docs/current/logical-replication.html)? And data partitioning? (See bottom of [this page](https://www.postgresql.org/docs/current/different-replication-solutions.html))
  - Peer-to-peer mechanism to ship database WALs (Write-ahead logs)
- Practice combining APIs in workflows by building an indexer for Google Drive 
  - See #68 
- Many of the above would also have interesting system administration & provisioning components ('datascience-devops')
  - Example: Terraform, Packer, and/or Nomad configuration to deploy the environments

**Comment by dlebauer** [comment]
and document in our protocols wiki

**Comment by Chris-Schnaufer** [comment]
These are being put into OSF. Next steps are review items and then writing tickets

**Comment by julianpistorius** [comment]
Added to protocols wiki:

https://osf.io/tzmhp/wiki/Ideas%20for%20interesting%20and%20fun%20stretch%20goals/
