### ISSUE TITLE
Run WebODM on CEREUS

### ISSUE THREAD

**Issue by julianpistorius** [az-digitalag/organization#488]
Placeholder only. Please see [issue on private repo](https://github.com/tyson-swetnam/cereus/issues/9).

**Comment by julianpistorius** [comment]
@Chris-Schnaufer & @dlebauer could you please test if you can use WebODM?

It needs an administrator account and password, but I'll let you set that up.

## How to use

```bash
autossh -M 0 -C -p 1657 -L 127.0.0.1:8000:127.0.0.1:8000 gpu06.cyverse.org 
# Or if not using autossh:
# ssh -C -p 1657 -L 127.0.0.1:8000:127.0.0.1:8000 gpu06.cyverse.org
```

Then open <http://localhost:8000> on desktop browser.

**Comment by dlebauer** [comment]
OK that is awesome! 

A few things:

- seems I need to specify my username:
   ```sh
   ssh -C -p 1657 -L 127.0.0.1:8000:127.0.0.1:8000 dlebauer@gpu06.cyverse.org
   ```
- When you say we need to set our username and password, is that for the WebODM itself? (I already have it set up for CEREUS)
- What would be required to make this a public facing UI?

**Comment by dlebauer** [comment]
WebODM is running at https://gpu06.cyverse.org:8080/dashboard/
