### ISSUE TITLE
Draft initial content for website

### ISSUE THREAD

**Issue by dlebauer** [az-digitalag/organization#5]

**Comment by dlebauer** [comment]
- [ ] Have meeting to discuss how to break existing documentation into site
- [ ] Create tasks on creating content

**Comment by dlebauer** [comment]
Compiling content in this folder https://drive.google.com/drive/folders/1koBlIf8QNPa4TOC_wq8XhaK_yPcFR_Sm

**Comment by Chris-Schnaufer** [comment]
Set up a time for us all to get together and work on this

**Comment by dlebauer** [comment]
- Waiting to meet w. Hannah to review the template for gathering content.
- then we will schedule a time to fill out template as a group.

**Comment by dlebauer** [comment]
Closing ... have created #24 and #25 as next steps
