### ISSUE TITLE
Document incubator steps in wiki

### ISSUE THREAD

**Issue by dlebauer** [az-digitalag/organization#501]
Some content that comes to mind:

* outreach, developing proposals
* project management - creating a timeline, plan for engaging with collaborators during project
* define contributions warranting authorship / acknowledgement (see e.g. stat support group, UW incubator, other definitions)
* how to start (as necessary, create or document github, data sources, osf
* how to end, manage time spent and wrapping up, 

TODO
* [x] create a wiki page under diag protocols
* [ ] have others review it

**Comment by KristinaRiemer** [comment]
Does the Incubator RFP page on the website cover this?

**Comment by dlebauer** [comment]
@KristinaRiemer no, this is to document our internal processes. Might be worth following up w/ UW group again to learn how they do it.

**Comment by KristinaRiemer** [comment]
Started an [OSF incubator page](https://osf.io/tzmhp/wiki/Incubator%20Program/). This is very much a draft with a lot of questions or possibilities in it!
