### ISSUE TITLE
Gather more info on grad-level course

### ISSUE THREAD

**Issue by KristinaRiemer** [az-digitalag/organization#505]
- [x] Meet with Austin about needs and culture from survey, esp in SNRE
- [x] Contact Kirsten Limesand about process
~~- [ ] Contact Kelly Jackson about curriculum committee~~
~~- [ ] Ask Izzy about how to help with the survey results~~
~~- [ ] Funding?~~ moved tasks to next sprint in #520

See [notes](https://hackmd.io/slVMsD4BRTmeTi0mEGhgXg) from meeting with Katy Prudic & Fiona McCarthy

**Comment by jessicaguo** [comment]
Additional [notes](https://hackmd.io/slVMsD4BRTmeTi0mEGhgXg) were taken in a meeting with Austin Rutherford. Fi reached out again about Tanya Hodges from the Yuma campus; initial email sent 6/3/2021.
