### ISSUE TITLE
Add DIAG description to Research doc

### ISSUE THREAD

**Issue by jessicaguo** [az-digitalag/organization#508]
- [x] Edit existing [blurb](https://docs.google.com/document/d/16a0L8Ue1nYbJFDOOoKQWfcKY0Kr7o7sRxhLtBaWaR-w/edit)
- [x]  Get approval from David
- [x] Add to [doc](https://docs.google.com/document/d/1EMMMm3WCTCcYEP1_iRLS4l0dys7z0uL5i39qIzcYxgY/edit#heading=h.xiy4g5g2w3p7)

Also organize Bayesian reading group
- [x] Send emails to potentially interested people
- [x] Organize a poll
- [ ] Write blurb on Bayesian reading group

Also contribute/edit Blake's [ms](https://docs.google.com/document/d/1U53Je7tEp50gdekHQiHzCS6H_u1T2qQ-/edit#)

**Comment by jessicaguo** [comment]
Modified blurb from Chris's suggestions. Added links to website where created. 

Emailed Mark and Bob about Bayesian reading group.

**Comment by dlebauer** [comment]
The first part of this has been completed in https://github.com/az-digitalag/organization/issues/336. It seems like the Bayes support group is a separate issue from what is implied in the title (perhaps just rename this one)?

**Comment by jessicaguo** [comment]
Yes, the reading group is a separate issue I was too lazy to create an issue for. It is still getting underway with Kelly Heilman. Once it's up and running, I will write a blurb for the main document.
