### ISSUE TITLE
Get ED2 running on UA HPC

### ISSUE THREAD

**Issue by julianpistorius** [az-digitalag/organization#51]
Need ED2 https://github.com/EDmodel/ED2 available for use by Kristina and myself. 

Two options - consider both in parallel:

1. Deploy singularity container - the dockerfile is here: https://github.com/PecanProject/pecan/blob/develop/models/ed/Dockerfile
2. Place a binary in a directory that is +rx (read/executable)

First step is to review w/ Julian, then Blake for guidance ...

**Comment by Sithyphus** [comment]
![2020-01-27 11_22_51-Microsoft Edge.png](https://images.zenhubusercontent.com/5dadfa4f58cac1000181cf89/77fc65be-f5a2-4485-85bf-a64481c3e480)
Here's what it looks like getting this model on the hpc. Error has to do with ED2IN file configuration which will likely have other tickets associated with it.
Below is a "quickstart" guide for getting to this point on the hpc
https://github.com/az-digitalag/model-vignettes/tree/ED2-HPC-Guide
