### ISSUE TITLE
DSFAS proposal resubmission

### ISSUE THREAD

**Issue by jessicaguo** [az-digitalag/organization#526]
Followup to #499
David:
- [x] Email program manager
- [ ] Contact collaborators

Jessica:
- [ ] Continue editing project documents
- [x] Migrate to OneDrive word doc
- [ ] Clean up citations - can use Mendeley

**Comment by dlebauer** [comment]
decided not to submit; will keep around for future opportunities

**Comment by dlebauer** [comment]
closing; we chose not to submit
