### ISSUE TITLE
Fix problems surfaced by Mypy

### ISSUE THREAD

**Issue by julianpistorius** [az-digitalag/organization#528]
See https://github.com/AgPipeline/issues-and-projects/issues/237 for more context.

https://github.com/AgPipeline/transformer-plotclip/pull/42 introduced Mypy. It surfaced three problems in the plot clip algorithm. Make the Mypy checks pass.

**Comment by julianpistorius** [comment]
References:

https://stackoverflow.com/questions/60537715/mypy-pop-error-for-none-object-is-not-iterable

**Comment by julianpistorius** [comment]
@Chris-Schnaufer see these two commits:

https://github.com/AgPipeline/transformer-plotclip/pull/42/commits/efc147b652bd73975e9ac4545c501865d8097ada

https://github.com/AgPipeline/transformer-plotclip/pull/42/commits/09a8d178035fc82c4df1fa5e8eae7dc755e7743a

**Comment by Chris-Schnaufer** [comment]
@julianpistorius These commits look good. Thanks for tracking down those issues.

Regarding the pylint error: perhaps have __internal__.get_plot_key_name() return a 2-tuple of None instead of returning None in place of a tuple?

**Comment by julianpistorius** [comment]
Good idea! Thanks. I'll try that.

**Comment by julianpistorius** [comment]
@Chris-Schnaufer I tried that, and it still triggered the Mypy error.

**Comment by julianpistorius** [comment]
@Chris-Schnaufer OK, it's ready.
