### ISSUE TITLE
Wrap up Organic Ag analysis part 1

### ISSUE THREAD

**Issue by dlebauer** [az-digitalag/organization#538]
* [x] check on data assumptions
* [x] re-run models
  * [x] update JAGS code to fig random slopes by state @jessicaguo

**Comment by dlebauer** [comment]
- need to implement advice from USDA statistician, perhaps reconnect

**Comment by dlebauer** [comment]
* received data from Virginia Harris at USDA 
* updated code, data, and models
* moved old data to data/old folder
* pushed changes to Github

TODO: 
* [ ] update JAGS code to fig random slopes by state @jessicaguo 
* [ ] move useful model output to derived_data and figures folders (these don't really belong in code/BUGS/etc/etc)
* [ ] Update README 
  * [ ] model documentation @jessicaguo 
  * [ ] data documentation @dlebauer
  * [ ] display results figures

**Comment by jessicaguo** [comment]
New mod3 completed, with updated figures and documentation. [PR4](https://github.com/az-digitalag/state_organic_ag/pull/4)

**Comment by jessicaguo** [comment]
Made changes to increase reproducibility and documentation. [PR5](https://github.com/az-digitalag/state_organic_ag/pull/5)
