### ISSUE TITLE
Test pipeline with larger data set

### ISSUE THREAD

**Issue by julianpistorius** [az-digitalag/organization#55]
- [x] Stand up clean stack
- [x] Trigger with sample data to make sure it works
- [x] Look at meeting notes to know which day(s) of data to get
- [x] Start local BETY
- [x] Deploy other extractors to Nomad
    - [x] Full field orthomosaic
    - [x] Mask
    - [x] Full canopy cover
- [ ] Metadata cleaning step
    - Figure out where that goes (see Pegasus workflow?)
- [ ] Use Globus to download the data (?)
- [ ] Figure out how to trigger loading the data (ask Chris?)

**Comment by Chris-Schnaufer** [comment]
Closing as no longer relevant
