### ISSUE TITLE
get PEcAn ED2 PRs merged

### ISSUE THREAD

**Issue by dlebauer** [az-digitalag/organization#592]
- [x] if this is ready for review, https://github.com/PecanProject/pecan/pull/2647 remove WIP tag
- [x] make sure all new parameters are documented in https://github.com/PecanProject/pecan/pull/2766 
    - I started this in https://github.com/PecanProject/pecan/pull/2766/commits/46937679436d95ef947e599ea06f7350f34d6dc7, but not sure my changes are correct
- [x] not ED2 related but while looking at PRs, please review https://github.com/PecanProject/pecan/pull/2658 and determine if it is still relevant or can be closed (@julianpistorius is also mentioned)

**Comment by KristinaRiemer** [comment]
All mentioned PRs have been reviewed and closed/merged.
