### ISSUE TITLE
Create a poster describing group activities

### ISSUE THREAD

**Issue by dlebauer** [az-digitalag/organization#6]
We need a poster to highlight the work we are doing. There are lots of campus-wide showcase events; the next one is the "Discover BIO5 Research to Innovation Showcase", which I think will be a good target. 

* Abstract due March 31 https://bio5.us5.list-manage.com/track/click?u=6e4e43b7b401ccef2b4683679&id=583037beea&e=cb279473e5
* Target date for initial poster draft (can be a sketch) should be April 7
* Poster will be presented April 18

https://mailchi.mp/bc2db55e7d14/save-the-date-discover-bio5-open-house-and-reception-1147401?e=cb279473e5

**Comment by julianpistorius** [comment]
@dlebauer done? The one from the IT Summit?
