### ISSUE TITLE
Draft up a poster advertising our incubator and office hours

### ISSUE THREAD

**Issue by Chris-Schnaufer** [az-digitalag/organization#610]
Draft up a post to be placed in department hallways advertising our incubator project and office hours. Have QR codes to our social media and web sites

Office Hours: designed to be less than 8.5"x11" (fit 2-4 per sheet)
Incubator project: designed to fit 8.5"x11"

**Comment by Chris-Schnaufer** [comment]
First attempt for Office Hours
![Office Hours 1.0.jpg](https://images.zenhubusercontent.com/5c14118eee1e975f1842e1c2/157b88b1-56b1-4d58-a3b6-09eafc65545f)

**Comment by Chris-Schnaufer** [comment]
First cut of Incubator document (8.5x11):

<img src="https://user-images.githubusercontent.com/45463434/133696309-5cc067bf-00f3-45db-96d6-00dae38e5fc8.jpg" width="500px" />

**Comment by dlebauer** [comment]
these look great - could we include our logo? https://drive.google.com/drive/u/0/folders/1cVbstWsvrBBoCWrkef4qk1G5UiPJ6aHA

I added a shorter url alias for the incubator at datascience.cals.arizona.edu/incubator 

I think the "What" contains "How" information. Are there editable versions of these documents available?

**Comment by dlebauer** [comment]
Also, I was going to bring this up at the quarterly review, but I am inclined to move office hours from Tue 8-10 to Tue 9-10 and Thur 4-5. 

The office hours could also advertise that people can schedule 1:1s based on availability.

**Comment by Chris-Schnaufer** [comment]
> I think the "What" contains "How" information. Are there editable versions of these documents available?

@dlebauer I am using Canva to create these. If you have an account, I believe I can share.

**Comment by Chris-Schnaufer** [comment]
I have combined the 2 posters onto one 11x8.5. IMO it's too crowded:

![Combined Office Hours Incubator.jpg](https://images.zenhubusercontent.com/5c14118eee1e975f1842e1c2/3fac8016-0a7b-465d-8632-14da9a2bbee9)
