### ISSUE TITLE
Wrap up organic ag analysis part 2

### ISSUE THREAD

**Issue by dlebauer** [az-digitalag/organization#618]
* [x] Update README 
 * [x] model documentation @jessicaguo 

 * [x] update figures / results table(s)
 * [x] display results figures  
* [x] report to Isaac

* [x] JG to review manuscript and add methods
* [x] DB to review manuscript

**Comment by jessicaguo** [comment]
[PR5](https://github.com/az-digitalag/state_organic_ag/pull/5) ready for review. Had to address a latebreaking discovery about the order of the response variables (area, number, sales), which previously had been (number, area, sales).
