### ISSUE TITLE
make pipeline compatible w/ PlantIT

### ISSUE THREAD

**Issue by dlebauer** [az-digitalag/organization#628]
For orthomosaic + geojson or shp --> plot level images + plot level masks + canopy cover workflow

* [x] create script that generates jx.json file
* [x] add plantit.yml file to repository
* [ ] add to planit portnoy.cyverse.org 
* [ ] make public

**Comment by Chris-Schnaufer** [comment]
https://github.com/AgPipeline/drone-makeflow/tree/plantit

**Comment by Chris-Schnaufer** [comment]
Waiting on Wes to confirm that updates are active and to provide instructions

**Comment by Chris-Schnaufer** [comment]
Closing. Replaced by #831
