### ISSUE TITLE
Draft incubator proposal for Satellite Guayule monitoring  

### ISSUE THREAD

**Issue by dlebauer** [az-digitalag/organization#630]
Basic workflow:

* 10 farms, 20 polygons per farm
* review available tutorials from Planet eg https://developers.planet.com/planetschool/calculate-an-ndvi-in-python/

Workflow: 
for each day a new image is available
1. download multispectral image from Planet
2. clip to polygons
3. calculate NDVI for each polygon
4. add that days' values for each polygon to a table
5. make data available on demand (as csv via https or otherwise)

TODO

* [x] create outline
* [x] request trial from Planet
* [x] get feedback from David
* [x] write draft
* [ ] share w/ Pete Waller (pwaller) & Diaa Elshikha (diaaelshikha), get their feedback, and submit

**Comment by Chris-Schnaufer** [comment]
Draft document available at: https://docs.google.com/document/d/12By1-KJs9bZwjaeVYqzjSNd_dxs-yv3f/edit?usp=sharing&ouid=106951433948198288799&rtpof=true&sd=true

**Comment by dlebauer** [comment]
I made some revisions and will reach out to Pete and Diaa
