### ISSUE TITLE
Clean up old OpenStack Images

### ISSUE THREAD

**Issue by Chris-Schnaufer** [az-digitalag/organization#641]
Clean up old OpenStack images under the TERRAREF project
![Screen Shot 2021-09-23 at 9.49.37 AM.png](https://images.zenhubusercontent.com/5c14118eee1e975f1842e1c2/61c4b55e-819c-4a4d-b5f7-5c6ac656a062)

**Comment by julianpistorius** [comment]
Done!

![Screen Shot 2021-12-02 at 09 32 02](https://user-images.githubusercontent.com/742633/144463587-e058d16c-83da-4917-b06a-103d1739302f.png)
