### ISSUE TITLE
Develop faster method for uploading large files

### ISSUE THREAD

**Issue by Chris-Schnaufer** [az-digitalag/organization#645]
Develop a method for quickly uploading large files.

The solution is to write a script that can be run on the server to split large files, upload the split parts of the file to iRODS, in parallel. Create a DE app that joins the files together.

**Comment by dlebauer** [comment]
Have you checked with Tony to see if there are other options, or in the wild to see if there are existing tools to do this?

**Comment by Chris-Schnaufer** [comment]
Tony's not aware of any
