### ISSUE TITLE
Create index and table of contents for the shared Google Drive

### ISSUE THREAD

**Issue by julianpistorius** [az-digitalag/organization#68]
For terraref, part of updating documentation

- [ ] Figure out the easiest and most maintainable way to do this
- [ ] Do it

**Comment by julianpistorius** [comment]
I think it _should_ be possible to do it with some combination of Zotero, OSF, and Google Drive APIs.

Link dump:

Drive:

- https://github.com/jay0lee/GAM/wiki/GoogleDriveManagement
- https://developers.google.com/apps-script/overview
- https://github.com/gsuitedevs/apps-script-samples

OSF:

- https://osfclient.readthedocs.io/

Zotero:

- https://github.com/mtekman/ZoteroGoogleDrive-PDFLinker
- https://tomsaunders.co.nz/zotero-with-google-drive/

Prior art:

- https://www.quora.com/How-can-I-create-an-index-of-Google-Drive-and-export-filepaths-to-Excel

This might be a fun mini-project (#48) to combine using APIs in a mini-workflow (Snakemake?)

**Comment by dlebauer** [comment]
close as not necessary stick w/ google drive searching
