### ISSUE TITLE
Reorganize betydb data entry documentation

### ISSUE THREAD

**Issue by dlebauer** [az-digitalag/organization#7]
Betydb data entry docs have been migrated to bookdown https://github.com/PecanProject/betydbdoc-dataentry

We need the following updates:
* Metadata section currently assumes data is being entered via the web interface
   * need to split this out into rails web UI, rails API, SQL, R, and BETYdb-YABA 
      * can include code that you wrote up and is currently in OSF
   * describe which of these will be the preferred methods (web UI, rails API and BETYdb YABA) and when
        * web UI 
            * for metadata is useful for a person who want to enter 1-10 records into a table; was originally designed around extracting meta-data from published papers; does not scale.
            * for uploads of long tables of traits by a person 
        * bulk upload api -- for automated bulk uploads 
        * BETYdb-YABA and its python client is for automated and bulk uploads to many of the tables
        * SQL and R are handy when you need features that the above don't implement and also for fixing data.

**Comment by Chris-Schnaufer** [comment]
Kimberly needs to discuss with David

**Comment by Chris-Schnaufer** [comment]
Convo resulted in list of tasks to be done at top of ticket.

**Comment by kimberlyh66** [comment]
Updates to the metadata entry section have been made. See pull request PecanProject/betydbdoc-dataentry#4 for details.

SQL function from PecanProject/bety#185 was not included since problems with function were mentioned (see comment linked above)

**Comment by Chris-Schnaufer** [comment]
Waiting for Pull Request to complete
