### ISSUE TITLE
Time series workshop

### ISSUE THREAD

**Issue by dlebauer** [az-digitalag/organization#710]
* **Title** intro to time series in R
* **Lead Instructor** David LeBauer
* **Helpers** TBD
* **Date** Dec 15

Tasks

Organizing the event

* [x] Identify presenter, title, description
* [x] Create an outline or link to materials https://github.com/NCEAS/nceas-training/blob/2021-11-delta/materials/sections/time-series-forecasting.Rmd
* [x] Create a Zoom meeting with registration
  * Include survey questions as appropriate
* [x] Write up announcement  
* [x] Add info to upcoming workshops section of [group website workshops page](https://datascience.cals.arizona.edu/workshops)
* [x] provide homework / background reading as appropriate (installation, references, etc)
* [ ] send out announcement (see list on Home page ... that list and this may move)
* [ ] send out reminders
    * How to do this on Zoom besides the automated registration reminder?
* [ ] Create pre and post workshop surveys
* [ ] Send out pre workshop survey

During Event 
* [ ] Provide time for post workshop survey
Follow Up
* [ ] follow up 
    * survey
    * invite to office hours

**Comment by dlebauer** [comment]
* meeting  registration link https://arizona.zoom.us/meeting/register/tZEvcOqtrDIvH9LzalphkiSGFKAdTpWPF40a
* workshop draft description https://hackmd.io/-hSaZbuzQI-gAPP3pASvRw?both#Early-December-2021-time-series

**Comment by KristinaRiemer** [comment]
The unfinished tasks from this should be moved to a new issue and addressed, especially followup with workshop attendees.
