### ISSUE TITLE
Draft CALS letter email

### ISSUE THREAD

**Issue by KristinaRiemer** [az-digitalag/organization#720]
Identify issues and solutions to those during group outreach hour week of Jan 3. See [notes](https://hackmd.io/fxo335XYQXGUpIm6c46TkQ). 

- [x] Identify purpose of email group
- [x] Decide on frequency of group use (no more than once a month, hopefully get down to quarterly)
- [x] Create myemma group form list for sign-ups
- [x] Compile list of emails for previous workshop attendees to add
- [x] **Draft initial email group email**
- [x] Revise group email

**Comment by dlebauer** [comment]
Also updated website, among other things (with Hannah's help) added 'book a meeting' links to the /people page
