### ISSUE TITLE
Advertise new positions

### ISSUE THREAD

**Issue by dlebauer** [az-digitalag/organization#738]
* [x] Circulate on job boards, twitter, slack channels
* [x] Update wiki page

**Comment by dlebauer** [comment]
Have posted to the following:

* [Earth Science Women's Network](https://eswnonline.org/online/earth-and-environmental-science-jobs/)
* ES Jobs `Es_jobs_net@ucar.edu`
* Academic Data Science Jobs Board https://academicdatascience.org/jobs
* US-RSE Job Board https://us-rse.org/jobs/policy/
* Rstudio Community https://community.rstudio.com/t/post-jobs-gigs-here/9254
* Twitter
  * hastags: #rstats #python #jobs
* Slack
  * ROpenSci
  * Carpentries
  * R4DS Online Learning Community 
  * Ecological Forecasting Initiative
  * US-RSE
  * ESIP (Earth Science Information Partners)
  * Rez-Baz
  * UA-Data Science

**Comment by jessicaguo** [comment]
Posted to:
NAU Ecoinformatics listserv
Slack: EDSIN
