### ISSUE TITLE
Review cdiff incubator proposal

### ISSUE THREAD

**Issue by dlebauer** [az-digitalag/organization#742]
* [x] Review and assess [proposal](https://docs.google.com/document/d/131a1uhPmNy5c7JWscLYNSJxB49qj8LUx/edit)
  * [x] David
  * [x] Kristina 
  * [x] Jessica
* [ ] ~~Create timeline with steps and milestones~~
* [ ] ~~Identify DIAG Lead~~
* [x] Request data examples and demo from lead
* [x] Reply to PI's and schedule a kickoff meeting

**Comment by KristinaRiemer** [comment]
@dlebauer which proposal?

**Comment by jessicaguo** [comment]
I have reviewed the proposal. My impression is that the asks could be divided into 3 separate proposals. First, they have an Excel file that is currently queryable by VBA macros that they want to be analyzed in R Bioconductor. Second, they want to create an SQL database. Third, they want a Shiny dashboard that can show retrieved data, visualizations, and analyses based on user-specified queries. Along they way, they would like to be trained on R, SQL, database management, web development, and Git Hub, which at least points to their willingness to work with us side-by-side. 

IMO, the proposed work vastly exceeds the scope of any incubator we've done so far and may require different DIAG leads for different portions. Our team does not currently have expertise in genomic analyses, but perhaps a new hire might.

**Comment by KristinaRiemer** [comment]
I have also reviewed this proposal. I think we won't know the extent of each of the three proposed steps until we get a better idea of how complicated and/or large their compiled dataset is? It also depends on how closely we can work with a domain expert and/or the current skill collaborator who wants to learn the technical skills. It definitely all seems doable.

**Comment by dlebauer** [comment]
Haven't identified a lead. But proposed starting in March / April, and perhaps this would be a good fit for a new hire :crossed_fingers:

**Comment by KristinaRiemer** [comment]
@dlebauer did you have a chance to create a followup issue for next steps?

**Comment by dlebauer** [comment]
@KristinaRiemer yes, follow up is #790
