### ISSUE TITLE
Review applicants and send interview invitations

### ISSUE THREAD

**Issue by jessicaguo** [az-digitalag/organization#767]
- [x] Meet on 2/2/2022 to decide on long list candidates
- [x] Decide on set of interview questions
- [x] Draft and send emails
- [x] Revise rubric/Google form for interview evaluation
- [x] Schedule meetings
- [x] Interview candidates:
- [x] JH
- [x] AG
- [x] LW
- [x] write up notes
- [x] Discuss with group who to move forward

**Comment by dlebauer** [comment]
will move all candidates forward to Maliaca's phone screen
