### ISSUE TITLE
Modify the cron job to delete older backups from the Welsch server

### ISSUE THREAD

**Issue by julianpistorius** [az-digitalag/organization#77]
..  once they're successfully uploaded to the Data Store.

Reminder: If setting up automated server deployments include these cron jobs.

**Comment by Chris-Schnaufer** [comment]
Except for year-end dumps, these should be replaced monthly, weekly, and yearly for the daily, weekly, and monthly backups (in that order)

**Comment by dlebauer** [comment]
no longer an issue
