### ISSUE TITLE
Make plan for BRIDGES workshop

### ISSUE THREAD

**Issue by jessicaguo** [az-digitalag/organization#793]
- [x] start HackMD and develop action plan
- [x] Get more info from program manager
- [x] create topics survey
- [x] send completed survey to program manager by 2/11

**Comment by KristinaRiemer** [comment]
[Notes in Hackmd](https://hackmd.io/4BMEpAbITDKVhXqUfF4iDw)
[Survey draft](https://docs.google.com/forms/d/1LfWAL_fg8odGoVjYcDyrjnqw2S2SqLg-68P9JDxT_fs/edit)
