### ISSUE TITLE
Chek new EFI forecasting challenge

### ISSUE THREAD

**Issue by dlebauer** [az-digitalag/organization#794]
* [x] For the PEG project, the new competition opens this week (Feb 7) so we need to make sure our forecasts are being submitted.
- [x] Previous weather and gcc data provided to Debasmita for 18 sites (up from previous 8)

Extra Credit: add a new model or two in the base PEG forecast file that leverage other types of models within the forecast project.

**Comment by jessicaguo** [comment]
Debasmita needs to fit the site-specific models based on previous data. Will create followup.
