### ISSUE TITLE
Add experiments_sites and sites_cultivars records for season 9 plot data (North and South)

### ISSUE THREAD

**Issue by kimberlyh66** [az-digitalag/organization#80]
Season 9 plots were added in #39. Now, need to associate sites with experiments and cultivars. 

Spreadsheet containing information on sites, cultivars, and experiments (provided by Maria):

North field: 
https://docs.google.com/spreadsheets/d/1-taHzWJ1lP_ME4rtJ8SHiia7N27VbZ030uYjoCNvHCE/edit#gid=44530443

South field:
https://docs.google.com/spreadsheets/d/1s7AYUjDLiODpYgURCbjKSji00CLaj_Nw37qly-SrP6I/edit#gid=1200493486

**Comment by kimberlyh66** [comment]
@dlebauer when you have time, can you run the following sql statements to add season 9 cultivars (for south field)?

[s9_south_cultivars.txt](https://github.com/az-digitalag/organization/files/3603005/s9_south_cultivars.txt)

**Comment by dlebauer** [comment]
@kimberlyh66 can you check that this is the correct file? It inserts into the sites table, not the sites_cultivars table

**Comment by kimberlyh66** [comment]
@dlebauer yes, this is the correct file. There are cultivars that are associated with season 9 south field sites that aren't in the database yet. The attached file above contains statements to add the new cultivars.

I am still working on the statements for the sites_cultivars and experiments_sites tables, so I will get those to you later.

**Comment by dlebauer** [comment]
@kimberlyh66 sorry for the misunderstanding - I had opened the wrong file!

**Comment by dlebauer** [comment]
@kimberlyh66 could you also provide update statements that add the 'ecotype' field for each cultivar?

**Comment by kimberlyh66** [comment]
@dlebauer Here are insert statements for experiments_sites and sites_cultivars.

experiments_sites: 
[s9_exp_site_south.txt](https://github.com/az-digitalag/organization/files/3618355/s9_exp_site_south.txt)

sites_cultivars:
[s9_site_cultivar_south.txt](https://github.com/az-digitalag/organization/files/3618357/s9_site_cultivar_south.txt)

**Comment by kimberlyh66** [comment]
Here are sql statements for north field plots.

cultivars:
[s9_cultivars_north.txt](https://github.com/az-digitalag/organization/files/3627664/s9_cultivars_north.txt)

experiments_sites:
[s9_exp_site_north.txt](https://github.com/az-digitalag/organization/files/3627668/s9_exp_site_north.txt)

sites_cultivars:
[s9_site_cultivar_north.txt](https://github.com/az-digitalag/organization/files/3627671/s9_site_cultivar_north.txt)

**Comment by kimberlyh66** [comment]
Notes for Maria (changes made to original spreadsheet):

* Removed `South Field` and `North Field` from site names (example: MAC Field Scanner Season 9 South Field Range 1 Column 1 E was changed to MAC Field Scanner Season 9 Range 1 Column 1 E)

* Changed experiment names to include MAC Season 9. Experiment names are MAC Season 9: South Field Border, MAC Season 9: GRASSL*RIO RILs, MAC Season 9: North Field Border, MAC Season 9: SAP

* Changed ecotype for SP1615 with specie id of 2588 from forage sorghum hybrid to Forage Sorghum, which is the ecotype in database.

**Comment by Chris-Schnaufer** [comment]
David needs to run 5 SQL scripts

**Comment by dlebauer** [comment]
I've run all of these queries
