### ISSUE TITLE
Scope out project with C. diff group

### ISSUE THREAD

**Issue by jessicaguo** [az-digitalag/organization#804]
- [x] Explore Excel sheet sent by Bryan
- [ ] Set up meeting to write out needs

**Comment by KristinaRiemer** [comment]
Started [notes](https://docs.google.com/document/d/1UGWnzkB031hUX6482maG20N13yr6u9Ig6T8A7oh2K78/edit) on data structure and how it might be converted to relational database.

**Comment by dlebauer** [comment]
Updated notes, sent email to schedule discussion w/ team in the next week or two
