### ISSUE TITLE
Create plan for monthly workshops

### ISSUE THREAD

**Issue by KristinaRiemer** [az-digitalag/organization#814]
Decide on topic (regex?), date, and instructors/helpers for March, April, and May

**Comment by jessicaguo** [comment]
March 30: Rmarkdown (Kristina lead, Jessica helper)
April 27: Dates and times in R (Jessica lead)
May 25: Crop growth modeling with BioCro (David lead)

**Comment by KristinaRiemer** [comment]
Thanks for getting that together, @jessicaguo! I think we can close this.
