### ISSUE TITLE
Run March session for spring workshop series

### ISSUE THREAD

**Issue by KristinaRiemer** [az-digitalag/organization#838]
- [ ] Send reminder email

Maybe prepare more content? Or do another Jeopardy style game? Any form of assessment before then? 

Possible activities include:
- [ ] More jeopardy as ice-breaker?
- [ ] Update from each person on their goals
- [ ] Ask whether they reference the curriculum page
- [ ] Sign up for our listserv
- [ ] Advertise jobs in our group
- [ ] Advertise incubator program

**Comment by jessicaguo** [comment]
[Notes](https://hackmd.io/X-fTVbS6Rp-Cysx_g-0kDw) on how to structure the session.

**Comment by KristinaRiemer** [comment]
Session completed and it went well! We had great discussion and got good feedback.
