### ISSUE TITLE
Make workshop series notes improvements

### ISSUE THREAD

**Issue by KristinaRiemer** [az-digitalag/organization#844]
Including the minor changes we actually made when teaching in Feb, and outline of restructuring.

**Comment by dlebauer** [comment]
Jessica wrote up last friday, Kristina will respond and wrap up

**Comment by KristinaRiemer** [comment]
I'm pushed my changes to the PR, feel free to edit and/or merge!

**Comment by jessicaguo** [comment]
Minor edits added and merged!
