### ISSUE TITLE
KR: Submit rstudio::conf registration and abstract

### ISSUE THREAD

**Issue by KristinaRiemer** [az-digitalag/organization#91]
- [ ] Submit travel authorization (Zaida)
- [x] Draft talk abstract & title
- [x] Submit abstract application
- [ ] Complete registration and payment (Zaida or David)

**Comment by KristinaRiemer** [comment]
Submitted talk/poster application on September 7. The TA and registration are waiting on wrapping up paperwork from EFI workshop trip.

**Comment by dlebauer** [comment]
This is done, yay!
