### ISSUE TITLE
Add documentation for connecting to Welsch BETYdb in OSF

### ISSUE THREAD

**Issue by KristinaRiemer** [az-digitalag/organization#97]
Followup to #75.

**Comment by KristinaRiemer** [comment]
I've started the document here: https://osf.io/a4p9n/wiki/Welsch%20PEcAn%20BETYdb/.

**Comment by KristinaRiemer** [comment]
If @julianpistorius or @kimberlyh66 want to review the instructions at the link in my previous comment? These are user instructions for accessing Welsch BETYdb, which Julian did in #75. It's very short, so should only take a few minutes to review.

**Comment by kimberlyh66** [comment]
I think the `@` sign is missing in between username and welsch.cyverse.org for the ssh tunnel command:
`ssh -N -L 127.0.0.1:5433:127.0.0.1:5432 -p 1657 username@welsch.cyverse.org`

Otherwise, the instructions look good!

**Comment by KristinaRiemer** [comment]
Good catch @kimberlyh66! I think there was an @ in the original code Julian sent to me? @julianpistorius can you confirm?

**Comment by KristinaRiemer** [comment]
Good suggestions @Chris-Schnaufer! I've included both of them.

**Comment by KristinaRiemer** [comment]
Assuming no one has any more comments on this, I'm going to consider this done. 

Instructions for how to connect to BETYdb with Postgres are in the OSF here: https://osf.io/a4p9n/wiki/Welsch%20PEcAn%20BETYdb/

**Comment by julianpistorius** [comment]
LGTM @KristinaRiemer
