### ISSUE TITLE
Create and fill out a matrix of skills in the group

### ISSUE THREAD

**Issue by dlebauer** [az-digitalag/organization#98]
Create a matrix that includes skills that we need in the group that can be used in hiring and understanding gaps, identifying experts, etc

**Comment by dlebauer** [comment]
First draft is here: https://docs.google.com/spreadsheets/d/1N95GgtAgvpQ9PhpiYwqWYewWu-FOzeIoQxzX2oldUuk/edit#gid=0

**Comment by KristinaRiemer** [comment]
We could use these for the categories on the group website for identifying everyone's skills.

**Comment by dlebauer** [comment]
@Chris-Schnaufer please fill out
